### ISSUE TITLE
Using Python 2?

### ISSUE THREAD

**Issue by privefl** [getian107/PRScs#1]
Using `../PRScs/PRScs.py --help`, I get the following error:
```
  File "../PRScs/PRScs.py", line 88
    print __doc__
                ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(__doc__)?
```

Does this mean that I can use PRS-CS with Python 2 only?

**Comment by getian107** [comment]
Currently yes - RPS-CS was coded and tested with Python 2.X

**Comment by privefl** [comment]
Still no plan for using Python 3 instead?

**Comment by getian107** [comment]
I just made some minor changes to the program; it should be Python 2/3 compatible now. Let me know if it doesn’t work.
