### ISSUE TITLE
Recommendation for combining scores by chromosome

### ISSUE THREAD

**Issue by privefl** [getian107/PRScs#12]
I understand that scores are derived by chromosome.
How do you recommend to combine the scores from all chromosomes?

**Comment by getian107** [comment]
You can either concatenate output files from all chromosomes or compute a polygenic score for each chromosome using PLINK's --score sum, and then sum up the scores.

**Comment by privefl** [comment]
OK, but when you need to choose the best `phi`.
Do you recommend to combine first all chromosomes, and then choose `phi`.
Or to choose the best `phi` per chromosome and combine afterwards.

**Comment by getian107** [comment]
We usually use the same `phi` across chromosomes. But I think choosing `phi` per chromosome is also a valid approach and probably provides more flexibility, although we haven't tested this approach.
