### ISSUE TITLE
Problem of reference panel

### ISSUE THREAD

**Issue by biostat0903** [getian107/PRScs#13]
Hi Tian, 
Thanks for your software. I would like to use a specific reference panel, rather than 1000 Genome. I build the `hdf5` and `snpifo` files, using the LD block information. But when I run PRScs, the error is:
````
  File "/net/mulan/home/yasheng/program/PRScs/PRScs.py", line 160, in <module>
    main()
  File "/net/mulan/home/yasheng/program/PRScs/PRScs.py", line 154, in main
    param_dict['n_iter'], param_dict['n_burnin'], param_dict['thin'], int(chrom), param_dict['out_dir'], param_dict['beta_std'], param_dict['seed'])
  File "/net/mulan/home/yasheng/program/PRScs/mcmc_gtb.py", line 55, in mcmc
    dinvt_chol = linalg.cholesky(dinvt)
  File "/net/mulan/home/yasheng/py3/lib/python3.7/site-packages/scipy/linalg/decomp_cholesky.py", line 91, in cholesky
    check_finite=check_finite)
  File "/net/mulan/home/yasheng/py3/lib/python3.7/site-packages/scipy/linalg/decomp_cholesky.py", line 40, in _cholesky
    "definite" % info)
numpy.linalg.linalg.LinAlgError: 1448-th leading minor of the array is not positive definite
````
Does this error mean that the LD matrix can not be inversed?
Best, 
Sheng

**Comment by getian107** [comment]
Hi Sheng,

It looks that there are some issues with the newly computed LD matrices. I attached some scripts that might be useful and briefly describe the steps wee took to build the LD reference panel below.

(1) QC the reference data (remove ambiguous SNPs, standard MAF, missingness and INFO filtering etc). Released reference panels are constrained to HapMap3 SNPs, which seems to be a good balance between prediction accuracy and computational cost.

(2) Divide the genome into blocks. We used the cutoff points already computed in this ref: Berisa, T. & Pickrell, J. Approximately independent linkage disequilibrium blocks in human populations. Bioinformatics 32, 283–285 (2016). If you want to build a reference other than the EUR, EAS or AFR populations, you might need to test their LDetect algorithm to define LD blocks. Note that computational cost scales with the size of blocks.

(3) Once you have the SNP list for each LD block, use PLINK to compute the LD matrix for each block (see calc_ld.sh attached).

(4) Save LD matrices into HDF5 format (see write_ldblk.py attached).

(5) You also need a file (like snpinfo_1kg_hm3 that comes with PRS-CS) which lists the SNPs included LD calculation (in the same order of SNPs in LD blocks and have matched A1).

Hope these help.

Best regards,

-Tian

**Comment by biostat0903** [comment]
Hi Tian, 
Thanks for your reply. First, I make my reference constrain to HapMap 3. Second, I use the block information to calculate LD matrix. Is that right? Thanks!

Best, 
Sheng

**Comment by getian107** [comment]
These are correct. You could modify the script I sent to calculate the LD matrices. From the error message, it looks that the LD matrices you computed were not non-negative definite and possibly not symmetric.

**Comment by cz354** [comment]
Hi Tian,

Where could the file 'calc_ld.sh' and 'write_ldblk.py' be found? 

Best,
Chi

**Comment by getian107** [comment]
Hi Chi- I'm not sure I can add attachments here. If you can reply back with your personal email I will send the files over.

**Comment by cz354** [comment]
Hi Tian,

Thank you very much. My email is zchi0947@gmail.com.

Best,
Chi

**Comment by daniel-hui** [comment]
Hi Tian,

Sorry to bring up an old post. We are trying to make a cosmopolitan ancestry reference panel from all of 1000 Genomes. Is this version of `write_ldblk.py` from this post https://githubmate.com/repo/getian107/PRScs/issues/20 still valid? I do not see the script on the GitHub for either PRS-CS or PRS-CSx currently. Thanks.

Daniel

**Comment by getian107** [comment]
Yes that's still valid. I'm not sure a reference panel from all 1000 Genomes samples would optimize prediction accuracy though. If your GWAS sample doesn't match the proportion of populations in the 1KG closely, then the LD in the reference panel wouldn't match the LD patterns in the GWAS summary stats very well, which might affect prediction performance.

**Comment by zjppdozen** [comment]
> These are correct. You could modify the script I sent to calculate the LD matrices. From the error message, it looks that the LD matrices you computed were not non-negative definite and possibly not symmetric.
> […](#)
> On May 24, 2020, at 9:13 AM, Sheng Yang ***@***.***> wrote: Hi Tian, Thanks for your reply. First, I make my reference constrain to HapMap 3. Second, I use the block information to calculate LD matrix. It that right? Thanks! Best, Sheng — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.



> Hi Chi- I'm not sure I can add attachments here. If you can reply back with your personal email I will send the files over.

Hi Tian,

Could you also share the file 'calc_ld.sh' and 'write_ldblk.py' with me?  My email address is zjppdozen@gmail.com.

Thanks and Best,
Yuexuan

**Comment by getian107** [comment]
Yes they are here: https://github.com/getian107/PRScs/issues/20

**Comment by zjppdozen** [comment]
> Yes they are here: #20

Hi Tian,

Thanks for sharing your code with me. They are really helpful. I created my own reference panel by following your instruction and code. However, when I run the software with my new reference panel, it gives this error message:

`##### process chromosome 22 #####`
`... parse reference file: ../../LDscore_blk/ldblk_1kg_eur/snpinfo_1kg_hm3 …`
`... 15414 SNPs on chromosome 22 read from ../../LDscore_blk/ldblk_1kg_eur/snpinfo_1kg_hm3 …`
`... parse bim file: ../../../../../data/genetic/biomarker/genetic_keep_498.bim …`
`... 111423 SNPs on chromosome 22 read from ../../../../../data/genetic/biomarker/genetic_keep_498.bim …`
`... parse sumstats file: ../../sumstat/PRScs_Kunkle.txt …`
`... 1029683 SNPs read from ../../sumstat/PRScs_Kunkle.txt …`
`... 14824 common SNPs in the reference, sumstats, and validation set …`
`... parse reference LD on chromosome 22 …`

`Traceback (most recent call last):
  File "/project/EngelmanGroup/ad_projects/work_in_progress/Yuexuan/PRS_method/code/PRScs/data/PRS/PRScs/PRScs.py", line 167, in <module>
    main()
  File "/project/EngelmanGroup/ad_projects/work_in_progress/Yuexuan/PRS_method/code/PRScs/data/PRS/PRScs/PRScs.py", line 158, in main
    ld_blk, blk_size = parse_genet.parse_ldblk(param_dict['ref_dir'], sst_dict, int(chrom))
  File "/project/EngelmanGroup/ad_projects/work_in_progress/Yuexuan/PRS_method/code/PRScs/data/PRS/PRScs/parse_genet.py", line 172, in parse_ldblk
    flip = [sst_dict['FLP'][jj] for jj in idx_blk]
  File "/project/EngelmanGroup/ad_projects/work_in_progress/Yuexuan/PRS_method/code/PRScs/data/PRS/PRScs/parse_genet.py", line 172, in <listcomp>
    flip = [sst_dict['FLP'][jj] for jj in idx_blk]
IndexError: list index out of range` 

1. Do you have any idea why this error message shows up?
2. Is PRS-CS sensitive to how the SNP name is defined? In the readme file, I saw that the SNP name is the rs-format. But in my analysis, I replaced the rsid for each SNP with a unique id (chr_bp, e.g., 1_102132312). Will this change affect the running of PRS-CS?

Many thanks,

Best,
Yuexuan

**Comment by getian107** [comment]
Hi Yuexuan - It's hard to diagnose the exact problem but I feel that the issue lies in the the snpinfo file that you created. 
The file needs to contain exactly the same set of SNPs included LD calculation; SNPs must be in the same order and have matched A1. Using a different ID format is fine, as long as SNPs in all files (summary statistics, snpinfo file, LD files) have the same format.

**Comment by NingNing-C** [comment]
Hi Tian,

Thanks for the amazing tool. I also want to build a LD reference panel for a population other than EUR, EAS and AFR based on the ~6000 samples in plink bed files. I tried to follow your instructions but stuck at step 2 : divide the genome into blocks. I’m quite new to this filed and wonder how to divide the genome into blocks if the data is not in EUR, EAS and AFR populations. 

1. First, I looked into the tutorial of ldetect, it seems that they use the genetic map based on CEU, YRI and ASN population and I’m not sure if it’s appropriate to use for my data. Also, they requires the effective population size as input, I have no idea how to get this. 
2. Besides, I’m wondering if I could use other tools to split the genome like snp_ldsplit() in bigsnpr, although they calculate the LD correlations first. 

I really want to see if the performance of PRS-CSx would increase if I used the customized LD reference panel, but faced problems mentioned above. Could you please kindly give some suggestions? I would highly appreciate that.

With Best Regards,
NingNing

**Comment by getian107** [comment]
Hi NingNing- Yes you can use any tools to partition the genome. The idea to identify LD blocks that are largely independent with each other. Re ldetect, you could email Kim, Joohyun <joohyun.kim@vumc.org> at VUMC (with me cc'd), who I have been collaborating with and has experience using the software.

**Comment by NingNing-C** [comment]
> Hi NingNing- Yes you can use any tools to partition the genome. The idea to identify LD blocks that are largely independent with each other. Re ldetect, you could email Kim, Joohyun [joohyun.kim@vumc.org](mailto:joohyun.kim@vumc.org) at VUMC (with me cc'd), who I have been collaborating with and has experience using the software.

Hi Tian,

Thanks for replying! I tried the snp_ldsplit() to divide the genome into 326 blocks and tried to use PRScs but failed with errors below.

![image](https://user-images.githubusercontent.com/78844302/172353235-aad58195-85f9-4adc-8cd9-9b0fb1b7e8e6.png)


It seems that the omega equals to 0, which leads to the error. Do you have any idea on this error?
Thanks!
Best,
NingNing

**Comment by getian107** [comment]
Hi Ningning- Similar to the question above from Yuexuan, I feel that the issue might be the snpinfo file that you created.
The file needs to contain exactly the same set of SNPs included in LD calculation; SNPs must be in the same order and have matched A1. I would double check the info file and make sure that it exactly matches with the LD panels you generated.

**Comment by dagherlab** [comment]
SOLVED. 
just see https://github.com/getian107/PRScs/issues/61 and I'm not gonna rebuild the reference panel. 



Hi, I have a follow-up question for one of the steps "(2) Divide the genome into blocks.". the paper you mentioned provides blocks file for hg19. what if I wanna build a reference panel for hg38? 

thank you!

Lang

**Comment by getian107** [comment]
I think the easiest approach would be doing a liftover to find the corresponding coordinates of the break points in hg38.
