### ISSUE TITLE
clumping and scoring

### ISSUE THREAD

**Issue by marine11** [getian107/PRScs#15]
Hello
I have about 1500 samples and about 5 million snps.

1. Using plink, a case-control statistic summary file was created. Is it better to use prs-cs after clumping? When clumping, only 80 snp remained, and when running prs-cs, only 15 snp remained.
Does prs-cs have no features like clumping?

2. I want to know more about how to use the plink score function. Is it correct to classify by p-value by putting --q-score-range and then get a score?

Thank you.

**Comment by getian107** [comment]
You should run PRScs on the original GWAS summary statistics (without clumping) as PRScs models LD patterns. Make sure you format the summary statistics following the instructions; in particular, SNP IDs must be in the rs format.

**Comment by marine11** [comment]
Thank you for quick response.
How to make score is 
plink 
    --bfile \
    --score (snp, a1, p-value header) \
    --q-score-range (p-value cutoff) \
    --extract (prs-cs output snps) \
    --out \ 
Is this the right way? 
I'm a beginner, so please explain in more detail. 
Thank you.

**Comment by getian107** [comment]
If you have the PRScs output, you can do

plink \
--bfile prefix_of_your_test_sample \
--score PRScs_output_filename 2 4 6 sum center \
--out filename

**Comment by marine11** [comment]
Thank you very much.

**Comment by marine11** [comment]
Hello
I have one question.
Why is the number of snps more in --phi=1e-5 than in --phi=1e-2?

Thank you.

2020년 8월 4일 (화) 오후 10:37, Tian Ge <notifications@github.com>님이 작성:

**Comment by getian107** [comment]
I'm not sure I fully understand this question. If two runs have identical input data and only differ in the value of phi, then the number of SNPs in the output file should be identical.  Smaller phi values assume a parser genetic architecture and impose stronger shrinkage on SNP effect sizes.
