### ISSUE TITLE
specify the bim file

### ISSUE THREAD

**Issue by kaibios0101** [getian107/PRScs#16]
Hi, tian. Thank you for your valuable package for PRS analysis. I have some confusion after fully read your paper and the readme file of the PRScs. 

The PRScs is designed to estimate the joint effect size of variants given the external LD reference panel and summary statistics dataset. However, the bim file of the validation dataset is needed to be specified in the PRScs.py. If we just utilize the PRScs.py to estimate the joint effect size, so why we need to assign the bim file in the PRScs.py? Maybe there is some information I miss.

bests

kai

**Comment by getian107** [comment]
Hi Kai- The reason for requiring a bim file is that we only want to calculate weights for SNPs that are available in the validation/testing set. We don't want to assign a large weight to a SNP that is missing in the test set which will affect prediction accuracy.

**Comment by getian107** [comment]
Hi Kai- The reason for requiring a bim file is that we only want to calculate weights for SNPs that are available in the validation/testing set. We don't want to assign a large weight to a SNP that is missing in the test set which will affect prediction accuracy.

**Comment by getian107** [comment]
Hi Kai- The reason for requiring a bim file is that we only want to calculate weights for SNPs that are available in the validation/testing set. We don't want to assign a large weight to a SNP that is missing in the test set which will affect prediction accuracy.

**Comment by kaibios0101** [comment]
Hi, Tian. I got it. Many thank !

Kai
