### ISSUE TITLE
change the direction of beta estimation

### ISSUE THREAD

**Issue by kaibios0101** [getian107/PRScs#17]
Hi, Tian. I have some confusion with the output results after running PRScs.py. 

First, the A1 is the effective allele and A2 is the alternative allele in the sinpinfo_1kg_hm3 file, is that right? 

Then, I found the direction of the posterior effect size may change and is inverse when comparing with the corresponding effect size in GWAS summary statistics. While A1 (usually is minor allele or effective allele) and A2 is also given in the bim file, I'm not sure the direction of the posterior effect size is inverted according to the A1/A2 in the sinpinfo_1kg_hm3 or the bim file.

Many thank for your help.

Kai

**Comment by getian107** [comment]
Hi Kai- PRS-CS automatically aligns SNPs and alleles between the GWAS summary statistics, reference panel and bim file, and accounts for strand flip and allele flip. The posterior effect sizes are given relative to the A1 allele in the output file, and the A1/A2 in the output is aligned to the bim file so when we calculate the PRS in the validation set using PLINK's score function we don't lose any SNPs.

**Comment by kaibios0101** [comment]
Hi TIan- Thanks for your clear answer, I totally understand.

Bests

Kai
