### ISSUE TITLE
different version of LD reference

### ISSUE THREAD

**Issue by kaibios0101** [getian107/PRScs#18]
Hi Tian- After downloading the LD reference panel (ldblk_1kg_eur.tar.gz), I found it's built on the GRCh37 version. If my bim file and summary statistics dataset are based on the GRCh38 version, should I use the LD reference panel of GRCh38 or where could I get it? I'm looking forward to your reply. Many thanks!

Kai

**Comment by getian107** [comment]
PRS-CS matches SNPs using rs IDs, A1 and A2; so if these information is accurate whether the bp coordinates are in GRCh37 or GRCh38 doesn't affect results. Alternatively you could convert your SNPs in GRCh38 to GRCh37 using e.g. the UCSC liftover tool: https://genome.ucsc.edu/cgi-bin/hgLiftOver

**Comment by kaibios0101** [comment]
Hi Tian-I got it, thanks for your answer. 

Bests,

Kai
