### ISSUE TITLE
Problem about reference panel

### ISSUE THREAD

**Issue by cz354** [getian107/PRScs#19]
Hi Tian,

When we make our own reference panel, Must it constrain to HapMap 3? Since I'd like to use 1000G_mac5eur as a reference panel which has 9254535 SNPs.

Best,
Chi

**Comment by getian107** [comment]
HapMap3 seems to be a reasonable balance between computational cost and prediction accuracy. For the current model fitting algorithm I don't think including 9m or 10m SNPs is computationally feasible, and there is no guarantee that including more SNPs improves prediction accuracy. You could try a different set of SNPs from HapMap3 but I'd constrain the total number of SNPs to 2m or less for now.

**Comment by cz354** [comment]
Thank you for your advice.
