### ISSUE TITLE
Making my own PATH_TO_REFERENCE

### ISSUE THREAD

**Issue by privefl** [getian107/PRScs#2]
Is it possible to do so (e.g. based on validation data)?

Because I have very few SNPs in common with the dataset you provide.

**Comment by getian107** [comment]
The reference directory contains precomputed LD for SNPs that are present on the 1KG and HapMap3 panels. It is possible to make your own reference panel but that requires recomputing all LD blocks. Alternatively you can impute your data set such that it has a better overlap with HapMap3 SNPs.

**Comment by Minta821** [comment]
I have a LD matrix based on HRC1.1, do I need to keep them any specific format, to get it run on PRScs?
It seems, in HDF5, the files are stored in blocks?

**Comment by privefl** [comment]
I'm trying to make my own LD files.
Is there any convention on the naming of the snpinfo/hdf5 files?
It does not seem to parse the reference file at all (it starts with the bim file, then errors), 
but work fine when using some of the LD ref folder that you provide.

**Comment by getian107** [comment]
Sorry I hardcoded file names in a way that is not very flexible...
See PRScs.py line 149-152 and parse_genet.py line 152-155.

**Comment by privefl** [comment]
I see, thanks
