### ISSUE TITLE
questions: LD 

### ISSUE THREAD

**Issue by complexgenome** [getian107/PRScs#20]
hi there,

thanks for this awesome tool. I'd be interested in using this package to create PRS for the population of interest.

The population in interest I've doesn't follow EUR, AFR or EAS genetics. I've in-house .bed/.bim/.fam (plink) files for them. I'd like to know how I can plug them to the the software.
I downloaded the data for LD shared on the github, but the file format were .hdf5 . I do not know how to convert plink to hdf5 or vice-versa.

**Comment by getian107** [comment]
Hi- you can refer to Issue #13 and follow the steps there to build your own reference panels.
The two scripts mentioned there can be downloaded using the two links below.
https://www.dropbox.com/s/somdbsceo4u6zjj/calc_ld.sh?dl=0
https://www.dropbox.com/s/66jv3qcc9624k39/write_ldblk.py?dl=0
Let me know if you have questions.
