### ISSUE TITLE
SNP effect size

### ISSUE THREAD

**Issue by zqsha** [getian107/PRScs#22]
Hi there,
Thanks for developing such an amazing toolbox for estimating the SNP effect sizes. Recently, we used PRS-CS to estimate the effect sizes of SNPs in ASD GWAS summary statistics. First, the toolbox worked well without bugs. But, we found the estimated effect sizes appear roughly zero centered. When we used these effect sizes to calculate the polygenic risk score (PRS) using PLINK --score in UK Biobank dataset. We found all subjects have negative PRS. Do you have any thoughts to explain this? Thanks.

Best,
Zhiqiang

**Comment by getian107** [comment]
PRS accumulates small effects across the genome. So if you didn't center your genotypes (i.e., variants are coded as 0, 1, 2) and SNP effects happen to be more negative on average, it is possible that most individuals have negative PRS. Usually the absolute value of PRS is difficult to interpret and we often focus on the relative risk between individuals in the target population (which means we can standardize the PRS to zero mean and unit variance). One possibility that may result in mean shift in the PRS distribution is that the ancestry of your target population doesn't match the ancestry of the GWAS sample, or your target sample has individuals of mixed ancestries. I'd suggest you visualize the distribution of PRS- it is supposed to be close to normally distributed. If it is highly skewed it might suggest issues in the PRS calculation and/or insufficient qc of the target sample.

**Comment by zqsha** [comment]
OK. Thanks for your reply. We checked that the PRS is normally distributed, which indicates it seems to arise from more negative than positive effects in the GWAS.
