### ISSUE TITLE
Minor README issue re: ldblk ancestries

### ISSUE THREAD

**Issue by carbocation** [getian107/PRScs#23]
The README currently states:

> PATH_TO_REFERENCE (required): Full path (including folder name) to the directory that contains information on the LD reference panel (the snpinfo file and hdf5 files). If the 1000 Genomes reference panel is used, folder name would be ldblk_1kg_afr, ldblk_1kg_eas or ldblk_1kg_eur; if the UK Biobank reference panel is used, folder name would be **ldblk_1kg_afr, ldblk_1kg_eas, ldblk_1kg_eur or ldblk_1kg_sas**. Note that the reference panel should match the ancestry of the GWAS sample (not the target sample).

(Emphasis mine.) The bolded part should read `ldblk_ukbb_{ancestry}` rather than `ldblk_1kg_{ancestry}`.

**Comment by getian107** [comment]
Thanks James for catching this!
