### ISSUE TITLE
Computational efficiency

### ISSUE THREAD

**Issue by opain** [getian107/PRScs#26]
Dear Tian,

I noticed that 10 minutes after PRScs has started running, it attempts to use all cores on a given node, even when only 1 core has been specified (i.e. sbatch -n 1). I noticed this using the htop command. By trying to run multiple jobs in parallel on a single core, a large amount of swap space (Swp) is used, reducing computational efficiency, taking PRScs ~5.5 hours to run one phi parameter for chromosome 1. I think this is due to use of scipy and pandas packages, which automatically try to use all available resources. Therefore, to resolve the issue I specify the number of cores available as follows:

export MKL_NUM_THREADS=$SLURM_CPUS_ON_NODE
export NUMEXPR_NUM_THREADS=$SLURM_CPUS_ON_NODE
export OMP_NUM_THREADS=$SLURM_CPUS_ON_NODE

This works well, restricting the analysis to the available cores, avoiding use of swap space, and PRScs then takes ~1 hour to run one phi parameter for chromosome 1, as reported in your publication. 

I don't think this is an issue with PRScs, but I thought other users may find this useful.

Many thanks,

Ollie

**Comment by getian107** [comment]
Dear Ollie,

Thanks so much for the suggestion! The three lines of code is exactly what I use when I submit PRScs jobs to our compute cluster. I have included the information in the readme so that everyone can see and benefit from it. Thanks again!

**Comment by opain** [comment]
Thank you!
