### ISSUE TITLE
Effect allele in the PRSCS output file

### ISSUE THREAD

**Issue by sn-GT** [getian107/PRScs#27]
Hi,

Thank you for developing PRS-CS. 

I was wondering which column corresponds to the effect allele for which the betas in column V6 are computed in the PRS-CS output file (head of file prscs_effects_refukbb_pst_eff_a1_b0.5_phiauto_chr22.txt shown below). The output file does not have headers to determine the effect allele: 
   V1         V2       V3 V4 V5            V6
1: 22  rs7287144 16886873  G  A  4.838310e-05
2: 22  rs5748662 16892858  A  G  7.408231e-05
3: 22  rs9605903 17054720  C  T  2.963325e-05
4: 22  rs5747940 17056415  T  C  2.513297e-05

Is the effect allele the same as A1 from the GWAS-summary-statistics-input-file OR is it one of the columns (V4 or V5) in the prs-cs output file ? 

Thanks

**Comment by getian107** [comment]
Hi- in the GWAS summary statistics, A1 specifies the effect allele. In the output file, the posterior beta in column V6 is calculated with respect to V4.

**Comment by sn-GT** [comment]
Thanks for clarifying!
