### ISSUE TITLE
problem with beta/effect size direction

### ISSUE THREAD

**Issue by ricardocortezcardoso** [getian107/PRScs#29]
I am using PRScs (auto mode) to calculate the LD-adjusted betas from a given summary stats (based on UKbiobank samples) using the 1000G or UKBB reference LD panel (provided). For this genome-wide analysis, I included only Hapmap3 SNPs that were also found in the target file (1000G EUR genotype data) from chr1-22. As a sense check, I have merged the betas and alleles from the original sumstats with the PRScs output of chr3, where most of the genome-wide association hits (p<5e-08) were located. Since the posterior mean is relative to A1, whenever A1 were reversed when compared with the sumstats, I multiplied PRScs beta by -1. I attached a table in which I describe whether the beta direction and A1 between the original sumstats and the PRScs output are the same or differ. Here is an example:

rs13097028: a1_ss=C; a2_ss=T; a1_prscs=T; a2_prscs=C; beta_ss=0.0577; beta_PRScs=1.47e-05

Any help in understanding why there is a change in direction in the betas compared to the summary stats betas would be greatly appreciated. 

![MicrosoftTeams-image (3)](https://user-images.githubusercontent.com/54276215/122898595-4cd57e80-d34b-11eb-80f8-f0d639a89165.png)

**Comment by getian107** [comment]
Effect size directions should be consistent other than a fraction of SNPs whose effects are close to zero.
Could you plot original effects in the summary statistics vs. posterior effects calculated by PRS-CS?

**Comment by EmadHassanin** [comment]
Dear Tian,

I also encountered the same issue. I realised no consistency between the original BETA and  posterior SNP effect sizes. 

please find attached a scatter plot between original effects in the summary statistics "BETA" vs. posterior effects 

I would like to ask if you would have a potential explanation of that?

![prscs](https://user-images.githubusercontent.com/49234147/126804549-63f50675-09f1-4b13-93dc-d2ff156f47dd.png)

**Comment by getian107** [comment]
There are two issues here- (i) PRS-CS posterior beta are standardized beta (i.e., assuming phenotypes and genotypes have been standardized); original marginal beta might scale with the phenotype. That's why the two beta's appear to be on different scales. (ii) PRS-CS aligns alleles to the validation bim file (and effect sizes are flipped where necessary) to maximize the number of SNPs in prediction. Therefore the effect allele in the original GWAS and PRS-CS output might be different. To compare effect size directions, you need to align the effect allele in the original GWAS with the A1 column in the output file and flip the direction of posterior beta where necessary.

**Comment by EmadHassanin** [comment]
@getian107 great thanks a lot for the explanation.

**Comment by ttumkaya** [comment]
Hi @getian107,

Thank you for the detailed explanation; I have encountered a similar issue.

Just a follow-up question, does that mean that one has to flip the PRS-CS output direction where necessary before passing the posterior betas to PLINK to calculate PRSs at individual level?

**Comment by getian107** [comment]
No- you don't need to do any posthoc processing before using PLINK's --score function to calculate PRS.
Alignment of the effect allele is only needed when you compare two effect size estimates that may be calculated with respect to different alleles.
Let me know if you need further clarification.

**Comment by ttumkaya** [comment]
Hi @getian107 

Thank you for the prompt response. Yes, I'd appreciate some clarification.

I've been trying to replicate the results that are published on the PGS catalog database for SCZ (PGS000135). When I calculate the posteriors for PGC2 SCZ GWAS summary statistics by using PRS-CS myself, more than half the SNPs end up having flipped directions (please see the attached plot). I am using the same parameters, LD reference etc. 

The PGS catalog weights and the weights that I calculate become very similar only after I multiply the weights by -1 where the alleles are flipped. The two dataset also produce flipped PRSs at the individual level when I use PLINK's --score function.

Any advice is much appreciated.

![PGS_cat_V_PGC2_GWAS](https://user-images.githubusercontent.com/9079513/129286212-81a6c58d-400b-4385-89b2-57200237681b.png)

**Comment by getian107** [comment]
PRS-CS aligns alleles to the validation bim file to maximize the number of SNPs in prediction.
Therefore, if the target bim files are different, the posterior effect sizes may be calculated with respect to different alleles even if the summary stats and reference panels are identical.
 
As a concrete example, assume we have the following SNP in the summary stats:

rs1234 A C +1

Then if the SNP in the bim file A is

rs1234 T G

The output posterior effects would be

rs1234 T G +1

If the SNP in the bim file B is

rs1234 G T

The output posterior effects would be

rs1234 G T -1

Without aligning the effect allele, the direction of the effect in the two output files appears to be different.
But in fact the two outputs are equivalent, and if you use PLINK's --score to calculate individual-level PRS, the two outputs would give you identical results.

Hope this helps.

**Comment by ttumkaya** [comment]
Thank you for the explanation @getian107 , it does make sense and helps a lot.

How would PLINK2 --score function would produce the identical results though? It takes three columns as input (ID, Effect Allele, Effect weight). Wouldn't the swapped effect/reference alleles in the SNP-level PRS affect the individual-level PRS results? At least this is what happens in my case, the direction is opposite for the two output files (please see the attached). 

Am I missing something obvious?

![PGS_cat_V_PGC2_GWAS_Ind_Level](https://user-images.githubusercontent.com/9079513/129391032-acb7050f-8e1f-43ed-ad1a-87d6bc68774b.png)

**Comment by getian107** [comment]
Using the same example, the two posterior effects are 

rs1234 T G +1

rs1234 G T -1

Assume the first allele is used as the effect allele, and for a given individual the genotype of the T allele is x.
Then in the first case the PRS is calculated as g*(+1)
In the second case the PRS is (2-g)*(-1)
So the two PRS only differ by a constant.
If both PRS are mean-centered, then they are identical.

Your individual-level PRS has opposite direction likely because when you converted the SCZ summary stats into the PRS-CS format you specified the alternative allele as the effective allele. The direction of all SNPs would be then flip and thus the direction of individual-level PRS is also flipped.

**Comment by ttumkaya** [comment]
The order of the REF/ALT alleles in the validation bim file was flipped compared to the SCZ summary stats. I guess PRC-CS aligned the summer stats to the reversed validation bim file, hence the flipped individual-level PRS.

Thanks so much again for your help @getian107 !
