### ISSUE TITLE
snpinfo_1kg_hm3

### ISSUE THREAD

**Issue by Minta821** [getian107/PRScs#3]
Hi,
I couldn't download snpinfo_1kg_hm3  from the https://www.dropbox.com/s/p9aqanhxvxaqv8k/ldblk_1kg_eur.tar.gz?dl=0
Regards,
Minta

**Comment by getian107** [comment]
Can you download ldblk_1kg_eur.tar.gz? snpinfo_1kg_hm3 is contained in the tar.gz package.

**Comment by Minta821** [comment]
Thanks  a lot, it's working now..
