### ISSUE TITLE
My code does not move to the MCMC step

### ISSUE THREAD

**Issue by jystatistics** [getian107/PRScs#31]
Hi Tian,

I'm running PRScs in my dataset and it seems that after they are checking the SNPs between reference, sumstats, and validation set, it is just stopping at the ... parse reference LD on chromosome 22 ...

Do you have any idea why my code is not moving to the MCMC step?

For another question, I know you mentioned the computational efficiency in README. 

export MKL_NUM_THREADS=$N_THREADS
export NUMEXPR_NUM_THREADS=$N_THREADS
export OMP_NUM_THREADS=$N_THREADS

But, I'm not sure where can I add these parameters to my script. Is it going with the PRScs.py command?

**_Addition information:_**

I have been implementing this code in the school server and my code cannot be passed to the MCMC step. 

I tried with same code in my desktop, but it is moving to MCMC step and eventually completed my job. I'm not sure why my code in the school server cannot be moved to MCMC step. 

Thank you for your help in advance!

**Comment by getian107** [comment]
Hi- The three export command can be put in the script where you call PRScs.py. I'm not sure why your job got stuck. Did it happen every time you ran PRScs on the server?
