### ISSUE TITLE
PRScs does not acknowledge n_gwas

### ISSUE THREAD

**Issue by petertanksley** [getian107/PRScs#32]
Hello, Tian!

I am trying to run PRScs on a computing cluster and I have run into an issue concerning the` --n_gwas `command. After loading python (2) and phdf5/1.8.16, I run the standard PRScs code in which I specify `--n_gwas=148164 \`. The job runs but it crashes after a few seconds and the only error the log file contains is the following: `* Please specify the sample size of the GWAS using --n_gwas`. 

I am not sure why PRScs is not acknowledging my specified GWAS sample size. Any help would be appreciated.
Cheers,

**Comment by getian107** [comment]
Hi- Could you share your full log output or the script you used to call PRScs? Thanks!

**Comment by petertanksley** [comment]
The log file only contained that one line asking me to specify the sample size. Here is the script I am running though:

```
module load python2
module load phdf5/1.8.16
PRScs.py --ref_dir ../../../../TUTORIALS/PRScs/REF_PANEL/ldblk_1kg_eur/ \
         --bim_prefix ../../../../TT_GENOTYPES/TEXAS_TWINS.1KG.EUR_noOutliers.chr1_22.updated.SNPs.maf1e-3.hwe1e-6.info90 \
         --sst_file= ../../INPUT/0_raw/3_CRP_1KG_GWAS_AJHG_2018_PRScs.txt \
         --n_gwas=148164 \
         --seed=973101 \
         --out_dir= ../../OUTPUT
```

**Comment by getian107** [comment]
The problem is caused by the space between `--sst_file=` and `../../INPUT/0_raw/3_CRP_1KG_GWAS_AJHG_2018_PRScs.txt`

**Comment by petertanksley** [comment]
Yup, that was the error. It appears to be running now. So simple, geez...
Thank you so much for the speedy reply! I really appreciate your help, Tian!
