### ISSUE TITLE
RuntimeWarning: invalid value encountered in cdouble_scalars

### ISSUE THREAD

**Issue by ttumkaya** [getian107/PRScs#36]
Hi Tian,

I'm using PRS-CS to calculate effect sizes for SNPs from a SZ GWAS study among African descent subjects, along with the AFR 1KG LD reference panel you have provided here on GitHub. I'm getting a warning and an error following after that:

Warning:
`/home/tumkata1/prog/PRScs/parse_genet.py:112: RuntimeWarning: invalid value encountered in cdouble_scalars
  beta_std = -1*sp.sign(beta)*abs(norm.ppf(p/2.0))/n_sqrt`

Error:
`.. MCMC ...
/home/tumkata1/prog/PRScs/mcmc_gtb.py:57: ComplexWarning: Casting complex values to real discards the imaginary part
  beta[idx_blk] = linalg.solve_triangular(dinvt_chol, beta_tmp, trans='N')
Traceback (most recent call last):
  File "/home/tumkata1/prog/PRScs/PRScs.py", line 167, in <module>
    main()
  File "/home/tumkata1/prog/PRScs/PRScs.py", line 160, in main
    mcmc_gtb.mcmc(param_dict['a'], param_dict['b'], param_dict['phi'], sst_dict, param_dict['n_gwas'], ld_blk, blk_size,
  File "/home/tumkata1/prog/PRScs/mcmc_gtb.py", line 56, in mcmc
    beta_tmp = linalg.solve_triangular(dinvt_chol, beta_mrg[idx_blk], trans='T') + sp.sqrt(sigma/n)*random.randn(len(idx_blk),1)
  File "/dlab/NS/tnt/user/tayfun/code/n2_SZ_PRS_GWAS_2020/.snakemake/conda/1f6e9f130ad14fd06826b6be42adbe4d/lib/python3.8/site-packages/scipy/linalg/basic.py", line 334, in solve_triangular
    b1 = _asarray_validated(b, check_finite=check_finite)
  File "/dlab/NS/tnt/user/tayfun/code/n2_SZ_PRS_GWAS_2020/.snakemake/conda/1f6e9f130ad14fd06826b6be42adbe4d/lib/python3.8/site-packages/scipy/_lib/_util.py", line 263, in _asarray_validated
    a = toarray(a)
  File "/dlab/NS/tnt/user/tayfun/code/n2_SZ_PRS_GWAS_2020/.snakemake/conda/1f6e9f130ad14fd06826b6be42adbe4d/lib/python3.8/site-packages/numpy/lib/function_base.py", line 485, in asarray_chkfinite
    raise ValueError(
ValueError: array must not contain infs or NaNs`

I checked the input files several times, but couldn't spot the issue.Have you ever encountered a similar error?

PS. The same pipeline works with a EUR GWAS study and the respective reference panel. 

Thanks,
Tayfun

**Comment by getian107** [comment]
Hi Tayfun- Looks like there are invalid p-values in the summary statistics. Could you send the command line you used to call PRS-CS and the summary statistics for the chromosome which produced the error?

**Comment by ttumkaya** [comment]
Hi Tian,

Thanks for the quick response! Here is the shell command I'm using:

`python /home/tumkata1/prog/PRScs/PRScs.py         --ref_dir=$(dirname /dlab/NS/tnt/user/tayfun/project/public_datasets/ldblk_1kg_afr/ldblk_1kg_chr21.hdf5)         --bim_prefix=$(dirname results/SZD/prscs_input/SZD_AFR.prs_input.bim)/$(basename results/SZD/prscs_input/SZD_AFR.prs_input.bim .bim) 	--out_dir=$(dirname results/SZD/prscs/afr/SZD.prs_pst_eff_a1_b0.5_phi1e+00_chr21.txt)/$(basename results/SZD/prscs/afr/SZD.prs_pst_eff_a1_b0.5_phi1e+00_chr21.txt _pst_eff_a1_b0.5_phi1e+00_chr21.txt)         --sst_file=results/SZD/prscs_input/SZD_AFR.prs_input.txt         --n_gwas=10070 	--phi=1.0         --chr=21`

And I just shared the GWAS summary statistics on Google Drive with your gmail account. Please let me know if you didn't receive it.

Thanks a lot!
Tayfun

**Comment by getian107** [comment]
The OR column has negative values. I think it is supposed to be BETA?

**Comment by ttumkaya** [comment]
Ah, I used gwas2vcf to annotate the rsIDs in my summary stats file, seems like it changed the effect size from OR to "Effect size estimate relative to the alternative allele" for some reason.

Changing this back to OR helped solved the problem, thanks a lot for your help Tian. Really appreciated!

Best,
Tayfun
