### ISSUE TITLE
Handling variable sample sizes?

### ISSUE THREAD

**Issue by kimsin98** [getian107/PRScs#37]
Some (meta) GWAS publish summary statistics with different sample sizes (N) for each variant, like the Alzheimer's studies [here](https://ctg.cncr.nl/software/summary_statistics).

How would you specify the sample size parameter in such cases?

**Comment by getian107** [comment]
The algorithm is not very sensitive to sample size variation. I'd filter out variants with low sample size (e.g., <50% of the total sample size) and use the total (effective) sample size in the algorithm.

**Comment by kimsin98** [comment]
Thank you for the advice. For most of variants, N is around 80% or more of the total sample size, so that sounds reasonable.

**Comment by Guo00158** [comment]
> The algorithm is not very sensitive to sample size variation. I'd filter out variants with low sample size (e.g., <50% of the total sample size) and use the total (effective) sample size in the algorithm.

Hi Getian, if we use the total **effective** sample size as the input, should we adjust the input SE by the effective sample size?

**Comment by getian107** [comment]
It's usually unnecessary - using the SE estimates that come with the summary statistics is the common practice.
