### ISSUE TITLE
Candidate gene

### ISSUE THREAD

**Issue by ooozcl** [getian107/PRScs#38]
Hi，
  May I ask whether PRScs can be used to analyze candidate genes at the level of candidate genes?

**Comment by getian107** [comment]
Hi- I assume you meant whether PRScs can be used to perform gene-level association testing? In theory you can although PRScs was designed for genome-wide polygenic modeling and we have never compared PRScs with gene-based association tests. I guess if you'd like to test association between the phenotype and candidate genes, dedicated gene-based methods might work better.

**Comment by ooozcl** [comment]
Thank you. Will the accuracy of the method be affected if only a few thousand SNP are included in the PRSCS method? For example, only the significant SNP of GWAS is included.

**Comment by getian107** [comment]
Yes- PRScs (and other Bayesian polygenic prediction methods) improves prediction relative to naive scoring methods (such as p-value pruning and thresholding) by modeling sub-threshold variants and variants in LD. So including only a filtered set of SNPs does affect the accuracy compared with using full GWAS summary statistics. But if you only have access to GWAS significant SNPs, then it wouldn't harm to use PRScs I think, although its advantage over pruning and thresholding might reduce.

**Comment by ooozcl** [comment]
Thank you
