### ISSUE TITLE
[SNP matching] For SNPs that have the same rsid

### ISSUE THREAD

**Issue by soowhee** [getian107/PRScs#39]
I assume PRScs matches SNPs based on rsid. 
But the thing is there are several SNPs that have the same rsid in the summary statistics. 
I handled this problem by assigning a unique rsid for each of SNPs that have the same rsid in the summary data and then replacing the rsid of matched SNPs with this in the target data in Hail v0.2. 
For rsid of LD reference, however, I don't know how to change it in hdf5 files. Do you have any idea on this matter?
Or can PRScs match SNPs some of which have the identical rsids?

Hope to hear from you soon!

**Comment by getian107** [comment]
Hi- PRScs matches SNPs based on rsid AND the two alleles, so it can handle SNPs of identical rsids with different A1 and A2. The reference panel doesn't contain SNPs with identical rsid. Hope this answers your question.
