### ISSUE TITLE
LDMatrix based on HRC1.1

### ISSUE THREAD

**Issue by Minta821** [getian107/PRScs#4]
I have a LD matrix based on HRC1.1, do I need to keep them any specific format, to get it run on PRScs?
It seems, in HDF5, the files are stored in blocks?

**Comment by getian107** [comment]
Building a new reference panel for PRScs to use requires some QC and preprocessing, dividing the reference into LD blocks, and saving LD matrices in HDF5 format. We found that PRS-CS is not particularly sensitive to LD reference as long as the GWAS and reference samples have matched ancestry. For example, in the PRScs publication, we compared 1KG EUR reference with a much larger in-sample reference panel (N~20K), and the prediction performances were virtually identical. We therefore pre-calculated and released LD reference panels derived from 1KG so that the users don't need to go through the reference building process. That said, we can help if you want to build your own reference panel, and I think it's a good idea for us to release an HRC EUR reference panel.

**Comment by Minta821** [comment]
It seems PRScs performs well with 1KG reference panel, but our data is imputed with HRC. While checking the overlapping SNPs, there are many millions SNPs missing. It's nice to have a reference panel which is based on HRC, we hope the performance also would further improve.

**Comment by getian107** [comment]
Currently we only use HapMap3 SNPs for prediction and the total number of SNP used by PRScs would be around 1m for well imputed GWAS. We think most common SNP variations may be tagged by HapMap3 SNPs and including multi-million SNPs in the calculation of PRS may not significantly improve its prediction accuracy, but we are also working on scaling the method to include all 1KG SNPs and investigate this question empirically.

**Comment by Minta821** [comment]
When we used LDpred with same data, it contains about 4 million variants and the performance is much higher than the PRScs..That why we are curious to include the HRC reference panel in the PRScs version.. It's nice to get some ideas (QC and other pre-processing required)  how to generate the HRC based reference panel which compatible with PRScs tool..

**Comment by getian107** [comment]
How many overlapping SNPs are included in PRScs in your analysis? We expect limited improvement when going beyond HapMap3 SNPs. Actually LDperd is also recommending restricting the analysis to HapMap3 SNPs, and they found that using more than 2 million SNPs typically reduces prediction accuracy: https://github.com/bvilhjal/ldpred/wiki/Q-and-A

**Comment by Minta821** [comment]
PRScs used only 1.02 million overlapping variants in the analysis

**Comment by getian107** [comment]
1.02 million sounds very reasonable. I'm suprised to learn that LDpred when using 4 million SNPs performs much better than PRScs. We are working on a project to allow PRScs to use multi-million SNPs while retaining computational efficiency, but that will probably take a while.

**Comment by cathynes** [comment]
Hi, I'm interesting in building our own ref panel using more SNPs and our own multi-population. I have used PRScsx for creating PRS based on only Hapmap SNPs. Event tho we see some improvement among Europeans, we do not see an improvement among other ancestry group particularly among African and we suspect that hapmap3 do not have a good representation of AFR. I will like to know if you can share your script for building LD matrix with us. This will allow us to use the population that best reflect the GWAS but also but also allow us to include more SNPs in the PRS?

**Comment by getian107** [comment]
Hi- You can follow the description here to build LD reference panels for PRS-CS:
https://github.com/getian107/PRScs/issues/20

We are working on a unified script for building customized reference panels and hopefully will make it available soon.

You can include more SNPs in the custom reference panel but also note that computational cost scales quickly with the number of SNPs and so far based on our own experience and results shared by other groups we haven't observed convincing evidence that including more SNPs beyond HapMap3 variants can robustly improve prediction accuracy. So at this stage I'd suggest not to include a very large number of SNPs (e.g., >2m) in the reference.
