### ISSUE TITLE
my PRS score range

### ISSUE THREAD

**Issue by forevertl** [getian107/PRScs#41]
Dear Tian, 
greetings! I have a question. I use about 100 SNPs to run both conventional PRS (via PRSice2) and PRS-cs. The score range /distribution is quite different. From PRSice2, the PRS scores for n=4000 participants are 0.13-0.29. From PRS-cs, the PRS score range is from -0.0007 to 0.13. 
question: is the difefrence of the range is as expected since PRSice2 use beta in the calucation directly and PRS-cs uses posterior effect estimate? Thank you very much. 

thanks, 
Lin

**Comment by getian107** [comment]
Hi Lin- Yes the difference in the scale of polygenic scores is expected. As you said, PRSice2 directly uses beta from GWAS summary statistics which depends on the scale of the phenotype, while posterior beta in PRS-CS is calculated based on the assumption that the phenotype has been normalized to zero mean and unit variance. Difference in the scale of PRS does not affect most performance metrics such as variance explained, AUC or odds ratio comparing top PRS percentiles with median/bottom percentiles.
