### ISSUE TITLE
Failing to parse the test summary stats

### ISSUE THREAD

**Issue by rchapleau** [getian107/PRScs#43]
Hello,

I was running into trouble with my own summary statistics files regarding an issue with local variable 'ref_dict' being referenced before assignment, so I tried to execute the test data.

My input was:
~PRScs/test_data$ python /home/rchapleau/PRScs/PRScs.py --ref_dir=/home/rchapleau/PRScs/refs/
ldblk_1kg_eur/ --bim_prefix=test --sst_file=sustats.txt --n_gwas=264973 --out_dir=fractprs --chrom=22

And the output was:
--ref_dir=/home/rchapleau/PRScs/refs/ldblk_1kg_eur/
--bim_prefix=test
--sst_file=sustats.txt
--a=1
--b=0.5
--phi=None
--n_gwas=264973
--n_iter=1000
--n_burnin=500
--thin=5
--out_dir=fractprs
--chrom=['22']
--beta_std=False
--seed=None

##### process chromosome 22 #####
... parse bim file: test.bim ...
... 1000 SNPs on chromosome 22 read from test.bim ...
Traceback (most recent call last):
  File "/home/rchapleau/PRScs/PRScs.py", line 167, in <module>
    main()
  File "/home/rchapleau/PRScs/PRScs.py", line 156, in main
    sst_dict = parse_genet.parse_sumstats(ref_dict, vld_dict, param_dict['sst_file'], param_dict['n_gwas'])
UnboundLocalError: local variable 'ref_dict' referenced before assignment

I'm executing this in python 3.8.10 on an Ubuntu 20.04 version installed on top of Windows 10.

Thank you,
Richard

**Comment by getian107** [comment]
Hi Richard- could you try removing "/" after ldblk_1kg_eur when specifying the reference directory? There also seems to be a typo in "sustats.txt" which is supposed to be "sumstats.txt" unless you intentionally changed the file name.

**Comment by rchapleau** [comment]
Thanks! Removing the "/" worked! It seems to me that I frequently run into syntax errors like that. D'oh! And thanks for catching my typo, that would have been another one to bother me!

Cheers!
Richard
