### ISSUE TITLE
Recommend reference panel?

### ISSUE THREAD

**Issue by euffelmann** [getian107/PRScs#44]
Hi Tian - You provide reference panels constructed form 1000 Genomes and UKB. Have you compared how well PRS-CS performs depending on which reference panel is used? The SBayesR authors recommend using an LD reference panel that is based on a larger sample (i.e. UKB in their case). I was wondering if you have a similar recommendation? Thanks!

**Comment by getian107** [comment]
Hi- I haven't comprehensively compared the two reference panels. From the relatively limited experiments, PRS-CS doesn't seem to be sensitive to the reference, and the two panels gave similar prediction accuracy. Thus I don't have a strong recommendation of one reference panel over the other for now.
