### ISSUE TITLE
Freezing at parse reference LD on chromosome 22 step 

### ISSUE THREAD

**Issue by dietina** [getian107/PRScs#45]
Dear Tian, 

I am running into an issue that prs-cs freezes at the step parse _reference LD on chromosome 22_ When running the test and my personal data, the program freezes at the same point and won't proceed to the next step after a whole day and night. 

The code is as follows: python PRScs.py --ref_dir=/path/prs-cs/ldblk_1kg_eur --bim_prefix=/path/test_data/test --sst_file=/path/test_data/sumstats.txt --n_gwas=200000 --chrom=22 --phi=1e-2 --out_dir=/path/prs_output/test

The program shows as and freezes at the last step: 

##### process chromosome 22 #####
... parse reference file: /path/ldblk_1kg_eur/snpinfo_1kg_hm3 ...
... 16464 SNPs on chromosome 22 read from /path/ldblk_1kg_eur/snpinfo_1kg_hm3 ...
... parse bim file: /path/test_data/test.bim ...
... 1000 SNPs on chromosome 22 read from /path/test_data/test.bim ...
... parse sumstats file: /path/test_data/sumstats.txt ...
... 1000 SNPs read from: /path/test_data/sumstats.txt ...
... 1000 common SNPs in the reference, sumstats, and validation set ...
... parse reference LD on chromosome 22 ...

Any idea how to correct this would be appreciated. Thank you!

**Comment by getian107** [comment]
Hi- I'm not sure what was the cause of this issue as we have never encountered this. Maybe try a different python version and a different machine?

**Comment by dietina** [comment]
Thank you Tian! I tried the test data on other machine and it worked. 

Another question is that I noticed there is 0 common SNPs on chromosome other than 22 (for example, 21 or 20). Is the test data designed to be so? And if we want to calculate for all 22 chromosomes, do we concatenate results from each individual chromosome, and take mean of them?

Thank you for your help in advance Tian :)

**Comment by getian107** [comment]
We only included SNPs on chr 22 in the test dataset. For real data applications, you can iterate through the 22 chromosomes which will produce posterior SNP effect sizes for each of the chromosome. You can then concatenate the 22 files to produce a set of weights for genome-wide SNPs. I'm not sure what you meant by "take the mean of them".

**Comment by dietina** [comment]
Thank you so much! I have 22 .bim files (chr1.bim to chr 22.bim)for the 22 chromosomes , and I would like to iterate through 22 chromosomes for the LD reference, can I know in this case, should I first concatenate the 22 files for chr1.bim, then concatenate the 22 files for chr2.bim, until all bims are analyzed?

**Comment by getian107** [comment]
If you have 22 bim files, one for each chromosome, you only need to run the model once for each bim, i.e., using --chrom 1 when the target bim is chromosome 1, --chrom 2when the target bim is chromosome 2, etc. You can then concatenate the 22 output files. You don't need to iterate through 22 chromosomes for each bim, because the output will not contain SNPs that are not in the target dataset.

**Comment by dietina** [comment]
Thank you very much Tian for your detailed instructions! I really appreciate them. I will close this issue. Thank you again for your time and help.

**Comment by BasilioCieza** [comment]
Hello guys,

I am also having the same issue of "Freezing at parse reference LD on chromosome 22 step" when I tried the test data...but I am running it on a cluster... I have tried many things but it is not working. I am copying my bash script in case I am missing something that is obvious for you guys:


N_THREADS=16
export MKL_NUM_THREADS=$N_THREADS
export NUMEXPR_NUM_THREADS=$N_THREADS
export OMP_NUM_THREADS=$N_THREADS

python PRScsx.py --ref_dir=path/reference_1000genomes/  --bim_prefix=path/test_data/test  --sst_file=path/test_data/EAS_sumstats.txt,path/test_data/EUR_sumstats.txt  --n_gwas=20000,10000 --pop=EUR,EAS --chrom=22 --phi=1e-2 --out_dir=output --out_name=final

**Comment by getian107** [comment]
Hi- I have been working on our clusters but have never encountered this issue so I'm not sure what's the root cause of this. Maybe try using one thread and running the program on different nodes using interactive mode. 

BTW- in the script the order you provide summary statistics and specify populations was inconsistent. I don't think this causes the problem but it will impact prediction accuracy in your analysis.
