### ISSUE TITLE
Multi-ethnic Polygenic Score

### ISSUE THREAD

**Issue by rameez500** [getian107/PRScs#48]
Hi Tian,

Hope you are doing well.

We have European summary statistics and African target dataset. 

Is it possible for us to calculate new beta using prs-cs method from European summary statistics and a reference sample of the same 
ancestry, such as from the UK biobank or 1000 Genome project data. Then can we use Africans target dataset to calculate score from the derived beta with prs-cs?

Thanks,
Rameez

**Comment by getian107** [comment]
Hi Rameez- Yes that's totally possible. You will probably find that PRS derived from EUR GWAS summary statistics has reduced predictive performance in your AFR target datasets compared with the predictions reported in EUR target datasets. But given the training dataset you have I think what you described is a very reasonable analysis to proceed.
