### ISSUE TITLE
PRScs fails to run with scipy-1.9.3

### ISSUE THREAD

**Issue by pettyalex** [getian107/PRScs#49]
Hello,

When evaluating this tool, I immediately ran into: 

`ImportError: cannot import name 'random' from 'scipy' `
with dependency versions:
```
h5py==3.7.0
numpy==1.23.4
scipy==1.9.3
```

At a glance, it looks like scipy may have historically exported the whole numpy namespace, but no longer does? 

https://docs.scipy.org/doc/scipy/release.1.4.0.html#backwards-incompatible-changes

I can't find any references in any of the scipy documentation to a "random" module or function, so I'm guessing that this should be numpy's random?

**Comment by getian107** [comment]
Thanks Alex- This happened very recently and I have merged your pull requests which fixed the issue.
