### ISSUE TITLE
Small overlap among the reference, sumstats and validation set

### ISSUE THREAD

**Issue by zqsha** [getian107/PRScs#5]
Hi Tian,

Thank you for developing such an amazing toolbox for polygenetic scores. When I run the analysis, I have 760 SNPs, but finally, only 58 SNPs were found among the reference, sumstats and validation set and calculated. I am sure 760 SNPs are in the sumstats and validation set. But, I am not sure these 760 SNPs are in the reference. Does it mean 702 SNPs (760-58) are not in the reference set?

Best,
Zhiqiang

**Comment by zqsha** [comment]
Here is the log:
##### process chromosome 1 #####
... parse reference file: /data/clusterfs/lag/users/zhisha/polygenetic_score/ldblk_1kg_eur/snpinfo_1kg_hm3 ...
... 92617 SNPs on chromosome 1 read from /data/clusterfs/lag/users/zhisha/polygenetic_score/ldblk_1kg_eur/snpinfo_1kg_hm3 ...
... parse bim file: /data/clusterfs/lag/users/zhisha/polygenetic_score/genetic_data/gwas_chr1.bim ...
... 1297023 SNPs on chromosome 1 read from /data/clusterfs/lag/users/zhisha/polygenetic_score/genetic_data/gwas_chr1.bim ...
... parse sumstats file: /data/clusterfs/lag/users/zhisha/polygenetic_score/phenotype1/gwas_pheno1_chr1_thr.txt ...
... 760 SNPs read from /data/clusterfs/lag/users/zhisha/polygenetic_score/phenotype1/gwas_pheno1_chr1_thr.txt ...
... 58 common SNPs in the reference, sumstats, and validation set ...
... parse reference LD on chromosome 1 ...
... MCMC ...
--- iter-100 ---
--- iter-200 ---
--- iter-300 ---
--- iter-400 ---
--- iter-500 ---
--- iter-600 ---
--- iter-700 ---
--- iter-800 ---
--- iter-900 ---
--- iter-1000 ---
... Estimated global shrinkage parameter: 9.62e-02 ...
... Done ...

**Comment by getian107** [comment]
Hi Zhiqiang,

Currently the reference panel only includes HapMap3 SNPs, and thus it's likely that it has small overlap with your data. PRS-CS is designed for summary statistics from well-imputed GWAS. In fact, Bayesian polygenic scoring methods are most useful when the GWAS has a good coverage of genome-wide variants. If you have <200K SNPs after intersecting with HapMap3 variants, the improvement of Bayesian methods over conventional polygenic scoring may be very limited, and I'd recommend you use the standard pruning and thresholding approach.

**Comment by zqsha** [comment]
OK. I see. Thank you for clearing it up.
