### ISSUE TITLE
Q about hm3 variants

### ISSUE THREAD

**Issue by gunns2** [getian107/PRScs#51]
Hi, 
Thank you for putting together such a great tool for researchers. I have a hopefully easy question, where does your list of hapmap variants come from? I've noticed some discrepancies between this set of variants and others (in particular the list of hapmap variants provided by the creators of ldpred2), and would love to understand where these discrepancies come from.

thank you,
Sophie

**Comment by getian107** [comment]
Hi Sophie- I used HapMap3 variants released here: https://www.broadinstitute.org/medical-and-population-genetics/hapmap-3
(see hapmap3_r1_b36_fwd_consensus.qc.poly.recode.map.bz2)

**Comment by gunns2** [comment]
Thank you!
