### ISSUE TITLE
Differences between Post_Effect_size in output file and Beta in GWAS 

### ISSUE THREAD

**Issue by gkarakoc** [getian107/PRScs#52]
Hi,
Could you please explain why Post_effect_size in the output file and Beta in GWAS have opposite signs?

Here is the output file:

V1         V2          V3            V4   V5            V6
22  rs1001213   34131736   A     G    -1.477724e-04
22  rs1001445   25168397   A     C     1.006345e-04

Here is the GWAS file

CHR         SNP         POS         A2    A1      OR          P                     BETA
22   rs1001213     34131736     G     A     1.07085    0.425683         0.02972864
22   rs1001445      25168397    C     A     0.976573   0.64141500   -1.029529e-02

Thanks,
Gul

**Comment by getian107** [comment]
Hi Gul- They have consistent direction of effects; it was just the reference allele was different.
For rs1001213, the reference allele in the GWAS is G while in the output the reference allele is A.
