### ISSUE TITLE
list index out of range

### ISSUE THREAD

**Issue by rameez500** [getian107/PRScs#55]
Hi Tian,

I hope you're doing well.

I have summary statistics in a format that looks like this:

SNP A1 A2      BETA           P
1   rs4562505  A  G  0.152891 7.29576e-07
2 rs183252502  A  T -2.091330 9.92719e-07
3   rs4892379  C  T  0.152728 1.09138e-06

And their categorical bases are:

      A                C           G
6276826 5435270 1035891

      C                 G          T
1039254 5445655 6263078

I have no issues running the PRScs tool with this sum stats. However, when I run the same format of sum stats with different categorical bases, it gives me the following error message as shown below. Could you please let me know how I can fix this type of error?

      A           C       	       T
3162683  554150  2713678

      C               G             T
2714878 3269555  446078

... parse sumstats file: sumstat_CUD_initiation.txt ...
Traceback (most recent call last):
  File "/home/rasyed2/Tool/PRScs/PRScs.py", line 167, in <module>
    main()
  File "/home/rasyed2/Tool/PRScs/PRScs.py", line 156, in main
    sst_dict = parse_genet.parse_sumstats(ref_dict, vld_dict, param_dict['sst_file'], param_dict['n_gwas'])
  File "/home/rasyed2/Tool/PRScs/parse_genet.py", line 61, in parse_sumstats
    if ll[1] in ATGC and ll[2] in ATGC:
IndexError: list index out of range

**Comment by getian107** [comment]
Hi- Thanks for reaching out. I'm not sure I fully understand your question. Could you elaborate a bit more? From the error message it seems to be a formatting problem in the GWAS summary statistics (PRS-CS didn't think the file has 5 columns).

**Comment by rameez500** [comment]
Yes, the GWAS summary statistics were initially problematic, but I was able to resolve the issue and now the analysis is running smoothly.

Thank you.
