### ISSUE TITLE
Effect Allele

### ISSUE THREAD

**Issue by rameez500** [getian107/PRScs#56]
Hi Tian, 

We have GWAS summary statics that was generated from RVTEST. Their format bit different like the output for effect size (BETA/OR) is from alternate allele. Is it possible to change the label like A1 = alternate allele and A2 = reference allele ? I am asking because PRS-CS assume BETA/OR come from A1 allele.

**Comment by getian107** [comment]
Hi -- I think in this case, when you prepare the summary statistics in PRS-CS's format, you can include the alternate allele as the 2nd column and label that as A1, and use the reference allele as the 3rd column and label that as A2. A simpler approach might be not making any change to the summary statistics but flipping the sign of the posterior SNP effect sizes or the individual-level PRS.
