### ISSUE TITLE
SNP id 

### ISSUE THREAD

**Issue by SoleilChenxu** [getian107/PRScs#57]
Hi Tian, I am applying PRS-CS on my target data. I am wondering if it's possible to use the method when the SNP is identified by based pair position instead of rs id in both summary statistics and  target dataset? I was trying to running the code but it seems impossible. Do you might have the experience about this?  Thanks a lot.

best,
Chenxu

**Comment by getian107** [comment]
Hi Chenxu- Thanks for reaching out. Currently PRS-CS requires the use of rs IDs in the summary statistics file and the target dataset. You would need to do the mapping before using the program. Sorry for the inconvenience.

**Comment by SoleilChenxu** [comment]
> Hi Chenxu- Thanks for reaching out. Currently PRS-CS requires the use of rs IDs in the summary statistics file and the target dataset. You would need to do the mapping before using the program. Sorry for the inconvenience.

Hi Tian,
Thank you for your prompt reply. I see! The I would map my target data first. 
Best,
Chenxu
