### ISSUE TITLE
No BIM Filter?

### ISSUE THREAD

**Issue by MatthewMaher** [getian107/PRScs#58]
Hi-  Thanks for PRScs*  - great tools.  

Question:  I understand PRScs produces a PRS model composed of SNPs that are in the three-way intersection of the base-GWAS, the LD-panel, and the target cohort.    And including that last one is critical to ensuring that a target cohort can be scored with 100% coverage (i.e. no missing variants).   

But then I see general [PRS-websites/portals where people post big PRS-models derived from PRScs (or other similar tools) for _no particular target cohort_](https://www.pgscatalog.org/score/PGS001780/).   I'm supposing this _usually_ works out okay because hopefully most target cohorts have good availability for the ~1.1M (or whatever it is) SNPs in the LD-ref panels, which limits what goes into the finished model, and thus the gap/loss due to missing SNPs would be minimal.     Am I understanding that correctly? 

So anyway, if I wanted to run PRScs like that - i.e. for **no particular target cohort** - and just rely on the filtering of the LD-panel, is there a shorthand way to do that (i.e. --nobim? ).   It seems like PRScs requires the --bim_prefix option.  Of course, I could create a fake BIM out of the base GWAS summary stats, and get the desired result.  But that seems like jumping through a pointless hoop, which makes me wonder if I'm missing a simpler way?  

Or maybe I'm misunderstanding the criticality of the BIM and the quality of all those non-target-specific models out there. 

Thanks for any info/insight

**Comment by getian107** [comment]
Hi - Yes you can build PRS for no particular target cohort. There is some risk that if a variant is assigned a large effect size but isn't available in the target dataset the predictive accuracy would decrease. But HapMap3 variants are usually well imputed and for the vast majority of polygenic traits/diseases, missing a small number of variants in the target datasets has minimal impact on prediction performance.

PRS-CS does require a bim input. You can create a fake bim from the SNP info file that comes with the software and includes all the variants on the reference panel.

**Comment by MatthewMaher** [comment]
sounds good - thanks for the info.
