### ISSUE TITLE
LD reference panel

### ISSUE THREAD

**Issue by HelenYSLin** [getian107/PRScs#59]
Hi Tian,
This might be a naive question - I am testing PRScs with sumstats from European samples but the target ancestry is African. Is it correct for me to use EUR LD reference panel or AFR's in such case? 
Thank you,

**Comment by getian107** [comment]
Hi Helen - The reference panel should always match the ancestry of the GWAS sample. So in this case if the GWAS summary statistics are derived from samples of European ancestries, an EUR LD reference panel should be used regardless of the ancestry of the target sample.

**Comment by HelenYSLin** [comment]
Thanks so much for your reply! That's really helpful to me
