### ISSUE TITLE
Parallelization doesn't give benefits

### ISSUE THREAD

**Issue by piotor87** [getian107/PRScs#6]
I'm currently using PRScs for calculating weights for a bunch of gwas summary stats, in order to calculate scores for our own data. One of the reasons our group decided to use PRScs was the possibility to run chroms separately, in order to minimize the costs in terms of memory if compared to other methods. However, unfortunately, the algorithm doesn't allow efficient parallelization, since the running times scale N times if N jobs are run in parallel. I tried the following test. I ran 2 identical jobs, one case chrom by chrom and the other in parallel:

```
parallel -j 1 "python2.7 -u /home/pete/Dropbox/Projects/CS-PRS-pipeline/PRScs/PRScs.py 
--ref_dir /mnt/disks/r5/PRS/ldblk_1kg_eur 
--bim_prefix /mnt/disks/r5/plink/R5.hm3.rsid 
--sst_file /mnt/disks/r5/PRS/cs/munge/AD_sumstats_Jansenetal.txt.munged.rsid 
--n_gwas 455258 
--out_dir /mnt/disks/r5/PRS/cs/weights/AD_sumstats_Jansenetal.txt.single  --chrom {}
 >  /mnt/disks/r5/PRS/cs/logs/AD_sumstats_Jansenetal.txt.{}.single.weights.log 
&& echo {} " 
::: 19 20 21 22

parallel -j 4 "python2.7 -u /home/pete/Dropbox/Projects/CS-PRS-pipeline/PRScs/PRScs.py
--ref_dir /mnt/disks/r5/PRS/ldblk_1kg_eur 
--bim_prefix /mnt/disks/r5/plink/R5.hm3.rsid 
--sst_file /mnt/disks/r5/PRS/cs/munge/AD_sumstats_Jansenetal.txt.munged.rsid
--n_gwas 455258
--out_dir /mnt/disks/r5/PRS/cs/weights/AD_sumstats_Jansenetal.txt.parallel  --chrom {} 
>  /mnt/disks/r5/PRS/cs/logs/AD_sumstats_Jansenetal.txt.{}.parallel.weights.log 
&& echo {} 
" ::: 19 20 21 22 
```

These are the running times for the `single` version:
```
##### process chromosome 19 #####
Function ran in 894.684458017 seconds
##### process chromosome 20 #####
Function ran in 1621.94453907 seconds
##### process chromosome 21 #####
Function ran in 801.826204062 seconds
##### process chromosome 22 #####
Function ran in 824.798161983 seconds
```
3540 seconds in total

and for the `parallel`:

```
##### process chromosome 19 #####
Function ran in 4215.7340591 seconds
##### process chromosome 20 #####
Function ran in 4924.37848806 seconds
##### process chromosome 21 #####
Function ran in 3828.55282807 seconds
##### process chromosome 22 #####
Function ran in 3968.17648602 seconds
```
4924 ( slowest run) in total

As you can see, the times grew roughly by a factor of 4, i.e. the number of jobs running in parallel. Chrom 19 and 20 scaled better because they were the last to run and therefore managed to have more resources towards the end.

I also noticed, that all cores (32) were being used at moderate level (~30%) regardless of the number of jobs being ran.

I'd say that, apparently, there is already some sort of multi threading going on, which is a good  thing, but on the other hand it doesn't allow for efficient parallelization. Is it intended? Is the method already structurally meant to run only one chrom at a time? 

Thanks

**Comment by getian107** [comment]
We didn't explicitly control the number of threads that the program can use, but it looks that some scipy operations are multi-threaded. As a result, you probably won't have much gain by parallelization on a single machine. By parallel computation, we meant if you have access to a compute cluster, you can submit 22 jobs, one for each chromosome, such that computation on different chromosomes can be paralleled. Sorry for any confusion.

**Comment by piotor87** [comment]
That makes perfect sense actually and I think it's extremely beneficial anyways that one can already take advantage of the multiple cores in a machine. I just wanted to make sure it was known/intended. 
Thanks!
