### ISSUE TITLE
BETA + SE still transformed to Z-scores?

### ISSUE THREAD

**Issue by euffelmann** [getian107/PRScs#60]
Hi Tian,

When BETA + P is provided as input, the P-values are transformed into Z-scores which PRScs works with. Now, just to make sure, when BETA + SE is provided as input, are these still transformed into Z-scores?

Thanks,
Emil

**Comment by getian107** [comment]
Hi Emil - Yes you are correct that PRScs always transforms inputs (BETA + P or BETA + SE) into z-scores and then into standardized effect sizes. The difference is that small P values are truncated and thus the absolute values of z-scores derived from P values will be capped; in contrast when BETA + SE is used as the input, z-scores can be arbitrarily large (or small) and are thus more accurate for highly significant loci.

**Comment by euffelmann** [comment]
Thanks!
