### ISSUE TITLE
A beginner's question about LD matrices

### ISSUE THREAD

**Issue by KaiYi1104** [getian107/PRScs#61]
Hi Tian,
Thanks for your tool.

I am trying to save LD matrices into HDF5 format by write_ldblk.py and calc_ld.sh.

1.Is it right if I have 5 SNP lists for LD blocks in chromosome 1, I need to compute the 5 LD matrix for each block?
2.In write_ldblk.py, what do "blk_chr" and "blk_size" mean?

Many thanks.

**Comment by getian107** [comment]
Hi - We would suggest using the released 1000 Genomes or UK Biobank reference panels as a starting point. PRS-CS is in general not sensitive to reference panels and these released panels work reasonably well in most cases. If you want to build your own reference panel, (1) we divide each chromosome into a number of LD blocks and compute one LD matrix for each block; (2) 'blk_chr' is the chromosome where each LD block is located and 'blk_size' is the number of SNPs each block contains. FinnGen has built their own reference panels and released the scripts which might be helpful: https://github.com/FINNGEN/CS-PRS-pipeline

**Comment by KaiYi1104** [comment]
Hi Tian,
Thanks for your quickly replying!

The 1000 Genomes or UK Biobank reference panels are built upon hg19 but I want to run PRS-CS with summary statistics and genotypes which are built upon hg38.

Is it right if I want to do this work, I should build my own reference panel?

Thanks again!

**Comment by getian107** [comment]
Hi - The genome build is usually not a problem. The base pair coordinates in the reference panel are for reference only and are not used anywhere in the computation. We use rs ID, A1 and A2 to match SNPs across reference panels, summary statistics and the target dataset. So as long as you have rs ID in your summary statistics you can use the software even if the genome build is different.

**Comment by KaiYi1104** [comment]
Hi Tian,
Thanks for your replying!
But, when I run the software with my new reference panel, it gives this error message:

##### process chromosome 1 #####
... parse reference file: D:/yi/prscs/test0705/ldblk_1kg/snpinfo_1kg_hm3 ...
... 6 SNPs on chromosome 1 read from D:/yi/prscs/test0705/ldblk_1kg/snpinfo_1kg_hm3 ...
... parse bim file: D:/yi/prscs/test0705/auto_uric_acid.bim ...
... 46257 SNPs on chromosome 1 read from D:/yi/prscs/test0705/auto_uric_acid.bim ...
... parse sumstats file: D:/yi/prscs/test0705/sumstat_TWB2.txt ...
... 446136 SNPs read from D:/yi/prscs/test0705/sumstat_TWB2.txt ...
... 6 common SNPs in the reference, sumstats, and validation set ...
... parse reference LD on chromosome 1 ...
Traceback (most recent call last):
  File "D:\yi\prscs\test0705\PRScs.py", line 167, in <module>
    main()
  File "D:\yi\prscs\test0705\PRScs.py", line 158, in main
    ld_blk, blk_size = parse_genet.parse_ldblk(param_dict['ref_dir'], sst_dict, int(chrom))
  File "D:\yi\prscs\test0705\parse_genet.py", line 157, in parse_ldblk
    hdf_chr = h5py.File(chr_name, 'r')
  File "C:\Users\USER\anaconda3\lib\site-packages\h5py\_hl\files.py", line 533, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, fcpl, swmr=swmr)
  File "C:\Users\USER\anaconda3\lib\site-packages\h5py\_hl\files.py", line 226, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py\h5f.pyx", line 106, in h5py.h5f.open
OSError: Unable to open file (bad object header version number)

Do you have any idea on this error?

Thanks!

**Comment by getian107** [comment]
Did you rebuild the SNP info file snpinfo_1kg_hm3? This file needs to contain the same set of SNPs in the same order as the LD reference panel.

**Comment by KaiYi1104** [comment]
I have successfully solved the problem
Thank you for your reply!
