### ISSUE TITLE
PRScs/mcmc_gtb.py:57: ComplexWarning: Casting complex values to real discards the imaginary part

### ISSUE THREAD

**Issue by Chris-Kato** [getian107/PRScs#62]
Thank you for developing PRScs.
I am currently getting the following error when using PRScs with the following code.
~~~~~~~~~~~~~~~~~~~~~~~~~~~

python2 ~/PRScs/PRScs.py --ref_dir=/XXX/ldblk_ukbb_eas --bim_prefix=/XXX/merged_VCFs --sst_file=/XXX/summs.txt --n_gwas=165522 --out_dir=/XXX/

~~~~~~
##### process chromosome 1 #####
... parse reference file: XXXX/ldblk_ukbb_eas/snpinfo_ukbb_hm3 ...
... XXX SNPs on chromosome 1 read from XXXX/ldblk_ukbb_eas/snpinfo_ukbb_hm3 ...
... parse bim file: /XXXX/merged_VCF.bim ...
... XXX SNPs on chromosome 1 read from /XXXX/merged_VCF.bim ...
... parse sumstats file: /XXXX/summs.txt ...
... XXX SNPs read from /XXXX/summs.txt ...
... XXX common SNPs in the reference, sumstats, and validation set ...
... parse reference LD on chromosome 1 ...
... MCMC ...
/XXXX/PRScs/mcmc_gtb.py:57: ComplexWarning: Casting complex values to real discards the imaginary part
  beta[idx_blk] = linalg.solve_triangular(dinvt_chol, beta_tmp, trans='N')
Traceback (most recent call last):
  File "/XXXX/PRScs/PRScs.py", line 115, in <module>
    main()
  File "/XXXX/PRScs/PRScs.py", line 109, in main
    param_dict['n_iter'], param_dict['n_burnin'], param_dict['thin'], int(chrom), param_dict['out_dir'], param_dict['beta_std'], param_dict['write_psi'], param_dict['seed'])
  File "/XXXX/PRScs/mcmc_gtb.py", line 62, in mcmc
    sigma = 1.0/random.gamma((n+p)/2.0, 1.0/err)
  File "mtrand.pyx", line 1983, in mtrand.RandomState.gamma
TypeError: Cannot cast array data from dtype('complex128') to dtype('float64') according to the rule 'safe'
~~~~~~~~~~~~~~~~~~~~~~~~~~~

Curiously, however, setting "--n_gwas" to 1000 or 10000 results in an error statement ("/XXX/PRScs/mcmc_gtb.py:57: ComplexWarning: Casting complex values to real discards the imaginary part
  beta[idx_blk] = linalg.solve_triangular(dinvt_chol, beta_tmp, trans='N')"), but the result is output.

Why does this happen?

**Comment by getian107** [comment]
Hi - This usually happens when beta is misspecified as OR or when the summary statistics file has some formatting issues (e.g., there are missing data or weird characters that are difficult to parse). I'd suggest you double check the summary statistics file to make sure that all effect sizes are available and real numbers.

**Comment by Chris-Kato** [comment]
Dear Dr. Tian,

Thank you for your prompt response!
As you pointed out, I mistakenly placed P in SE. The issue has now been successfully resolved.

I greatly appreciate your assistance!!
