### ISSUE TITLE
about score

### ISSUE THREAD

**Issue by SoleilChenxu** [getian107/PRScs#63]
Hi Tian,

I have a question about using the new computed effect size of SNPs to generate PRS. If I understand correctly, basically all the SNPs that have been placed a new effect size should be used to construct the score right? It that necessary to calculate the score under a range of p-value thresholds like what is usually conducted by clumping and thresholds method? Could you maybe talk more about the P value that has been included in input file? Thanks!

Best,
Chenxu

**Comment by getian107** [comment]
Hi Chenxu -- Yes all SNPs in the output file should be used to create the score in the target dataset. No additional p-value thresholding or filtering is needed. The P-values in the input file are marginal p-values from GWAS and are used to calculate the z-scores of marginal effect sizes. They should not be used at the scoring step.

**Comment by SoleilChenxu** [comment]
Hi Tima,

Thanks for you prompt reply. That's clear! 

Best, 
Chenxu
