### ISSUE TITLE
How to create own reference Panel?

### ISSUE THREAD

**Issue by Sohambiswas8** [getian107/PRScs#64]
Hi Tian, 

I am an amateur in population genomics and computing LD with respect to a particular set of SNPs. 

When I understood the PRS-CS tool's workflow, I needed to create my own LD reference panel for my project study. For a sample population, I have my own lab-generated and mapped SNPs into chromosomes in VCF files. I saw you provided already constructed LD reference panels for 5 superpopulations. My question is, how to construct such an LD reference panel based on GRCh38 Genome build from my own VCF files, in the first place? 

Can you please outline the workflow or help me with any tutorial or already published pipeline? 

Thanks in advance, 
Soham

**Comment by getian107** [comment]
Hi Soham - We would suggest using the released 1000 Genomes or UK Biobank reference panels as a starting point. PRS-CS is in general not sensitive to reference panels and these released panels work well in most cases.

If you do want to build your own reference panel, you can refer to
https://github.com/getian107/PRScs/issues/20
https://github.com/getian107/PRScs/issues/13

FinnGen has also built their own reference panels and released the scripts which might be helpful: https://github.com/FINNGEN/CS-PRS-pipeline

**Comment by Sohambiswas8** [comment]
Hi Tian, 

Thank you for the linked threads. I am performing the standard QC steps for the SNPs using PLINK and R packages. However, I am sure, in later steps, I need help as I am a first-timer in this kind of project. 

Therefore, can this thread remain open? I am quite sure I will face more doubts while performing the subsequent steps. 

Thanking you, 
Regards,
Soham

**Comment by Sohambiswas8** [comment]
Hi, 

Thank you for your previous guidance. I followed the Issues #20 and #13 . 

Now, before starting with my own VCF files to create a custom LD reference panel, I first looked into the 1KG SAS reference panel (as I am only interested in South Asian population), and decompressed hdf5 format. 

I am showing the code snippet for better clarification:

`# test on chr1 file

dataset_chr1 = h5py.File('ldblk_1kg_sas/ldblk_1kg_chr1.hdf5','r')
print(dataset_chr1.keys())
len(dataset_chr1.keys())
block1 = dataset_chr1['blk_1']
block1.keys()
print("LD block data: {}".format(block1['ldblk']))
print("SNP list data: {}".format(block1['snplist']))`

As output, I got an LD matrix of 329 SNPs and from the '`snplist'`, I now have the list of 329 SNPs in '`blk_1`' of chromosome 1. But here I have a few queries and was unable to understand: 

1) Many values in '`blk_1`' LD matrix are negative. If they are R^2 values how they are negative? Or, they are D or D' values?
2)  Will the order of the SNPs in the LD matrix (row and column wise) be the same as the order of SNPs in '`snplist`' and that of `snpinfo_1kg_hm3` file as well? 
3) If I understood, the reference panel has been built upon GRCh37 as the SNP coordinates match with this genome build. Is it correct? 
4) I manually tried to calculate D' and R^2 value of first two SNPs i.e. rs3131972 and rs3131969 by [LDPair](https://ldlink.nih.gov/?var1=rs3131972&var2=rs3131969&pop=GIH%2BPJL%2BBEB%2BSTU%2BITU&genome_build=grch37&tab=ldpair) tool on GRCh37 and 5 sub-populations of SAS. Result D' and R^2 values are different (0.9863, 0.8064 respectively) than computed in the panel. What can be the possible reason? Or have I missed something in the process? Although the MAF values reported are similar to what LDpair is generating. 

It would be really helpful If you kindly look into the issue and resolve my doubts or provide me with a possible solution for any glitch that I may have caused. 

Thanking you,
Soham

**Comment by getian107** [comment]
Hi Soham,

1. Values in the LD matrix are correlations between genotypes (and thus can be both positive and negative).
2. Yes the order of the SNPs in the LD matrix must be the same as the order of SNPs in 'snplist' and 'snpinfo_1kg_hm3'.
3. Correct - but note that SNP coordinates are not used in SNP matching or calculation; they are included for reference only.
4. LD matrices were calculated from 1000 Genomes reference panels using PLINK (--r). They can thus be slightly different from LD estimated from other reference panels or estimated using a different measure such as D'.

**Comment by Sohambiswas8** [comment]
Hi, 

Thank you so much for the explanation. This is really helpful. 
So I want to replicate the workflow in my own VCF data but before that, I want to confirm the 1000 Genomes reference panel that you used to calculate LD matrices. 

I found the 1000 genomes FTP site for Phase 3 data panel [here](https://ftp.1000genomes.ebi.ac.uk/vol1/ftp/release/20130502/) 
https://ftp.1000genomes.ebi.ac.uk/vol1/ftp/release/20130502/ 
Is this reference genotype (VCF) panel that you have used? Or I am still missing something? 

And also, as you said, values in the LD matrix are correlations between genotypes which are calculated by PLINK (--r), I think the basic command would be, 'plink --file/--bfile _myfile_ --r'. Am I right? Apology but I am a beginner in using Plink and have started to read the official documentation. So wanted to confirm this as well. 

Thanks,

**Comment by getian107** [comment]
Hi Soham,

Yes this is the source file but I think I used the MAGMA version that went through some quality control:
https://ctg.cncr.nl/software/magma

There are two scripts shared in issue #20; calc_ld.sh shows how LD matrices were calculated.

**Comment by Sohambiswas8** [comment]
Hi Tian, 

Thank you so much for your previous response. I have successfully replicated the workflow you used to create the SAS LD reference panel with the genotype correlation values also matching. Except the step 2 you mentioned in #13 to divide the chromosome into independent LD blocks, is difficult for me. 

I have in-house genotype VCF data with 823 samples generated explicitly from sequenced Indian populations. Hence, it might be that they won't follow the AFR, ASN and EUR LD patterns. So my questions while following the LDetect tutorial:

1) If I want to use LDetect on my own data, what would be the interpolated genetic map required? Is there any already created at least for SAS population, if it is reasonable to use? Can you provide me with any useful resources for this?
2) Our in-house data is built on hg38 and LDetect is supported on hg19. Will it be still okay to use LDetect?
3) How to know the effective population size and cut-off for creating a covariance matrix?
4) Can you suggest any other tool like LDetect to use to split chromosomes into largely independent LD blocks?  

I saw the same issue has been mentioned in the thread but couldn't find any help with that. 

Thank you in advance.

**Comment by getian107** [comment]
1KG subpopulation genetic maps: https://ftp.1000genomes.ebi.ac.uk/vol1/ftp/technical/working/20130507_omni_recombination_rates/
https://mathgen.stats.ox.ac.uk/impute/1000GP_Phase3.html
You can perhaps interpolate genetic maps and average effective sample sizes for SAS subpopulations.

I haven't run LDetect myself but think it should work on hg38.
An alternative, more recently published algorithm is: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC8696101/

**Comment by Sohambiswas8** [comment]
Thank you so much for constant helps
