### ISSUE TITLE
How to find optimal phi value

### ISSUE THREAD

**Issue by Dragonfly1108** [getian107/PRScs#65]
Hi Dr. Ge,

I'm using the newest version prs-cs to calculate UKB PRS.  I have about 1,300,000 GWAS sample size and 30,000 sample in target dataset.  Should I just use PRS-CSauto or do a small-scale grid search (e.g., phi=1e-6, 1e-4, 1e-2, 1) to find the optimal phi value in the validation dataset often improves perdictive performance.  If I use (phi=1e-6, 1e-4, 1e-2, 1),  what should I do to find out the optimal phi value ?

Thank you!

Sincerely,
Dargonfly

**Comment by getian107** [comment]
Hi Dargonfly - Both approaches are valid. If you'd like to use grid search, you need to split your target samples into independent validation and testing sets. You can then select the phi value that works best in the validation set, and evaluate the final PRS in the testing set. The auto algorithm is slightly easier to implement as you don't need to split target samples. For sufficiently powered GWAS, the two approaches often given similar predictive performance.

**Comment by Dragonfly1108** [comment]
Thanks for the quick reply. I have divided the validation set and test set and have run the grid search on the validation set, but now I don't know how to determine the optimal phi value. Can you help me?

**Comment by getian107** [comment]
If you tried, say, four different values of phi, you can calculate four PRS in your validation dataset, each corresponding to one value of phi. You can then assess which PRS gives the best predictive performance in your validation set, using a performance metric such as variance explained (for quantitative traits) or AUC (for binary traits). The phi value that corresponds to the best PRS will be the optimal phi. You will then evaluate the optimal PRS in the test set.

**Comment by Dragonfly1108** [comment]
I got it. Thank you!
