### ISSUE TITLE
How to convert hdf5 format to Plink bim,bed,fam format

### ISSUE THREAD

**Issue by lhl-0419** [getian107/PRScs#66]
Hi Tian,

I am happy to use the European reference panel of the UK Biobank, but I would like to know if there is a way to convert the obtained hdf5 files into Plink format bim,bed,fam files during use？

Thank you!
lhl

**Comment by getian107** [comment]
Hi - We use hdf5 format to save LD matrices which are not individual-level data and don't have corresponding bim/bed/fam files. Does this answer your question?

**Comment by lhl-0419** [comment]
Thank you for your answer!
