### ISSUE TITLE
plink --score

### ISSUE THREAD

**Issue by lhl-0419** [getian107/PRScs#69]
Hello
It was a pleasure to use PRScs. In the process of running PRScs, I used 1000 genomes from Europe, the GWAS summary statistics, the East Asian test data, and obtained a posterior SNP effect size estimate for 22 chromosomes based on the code command of PRScs. Then I linked the output files of all the chromosomes and used Plink-score to generate a polygenic score at the individual level. And we get something like this

FID | IID | PHENO | CNT | CNT2 | SCORESUM
HG00403 | HG00403 | -9 | 1054938 | 297483 | -0.0229848
HG00404 | HG00404 | -9 | 1054938 | 296777 | 0.0432846
HG00406 | HG00406 | -9 | 1054938 | 295133 | -0.00838818
HG00407 | HG00407 | -9 | 1054938 | 297197 | 0.0208002
HG00409 | HG00409 | -9 | 1054938 | 295825 | 0.0208026
HG00410 | HG00410 | -9 | 1054938 | 297630 | 0.0095
HG00419 | HG00419 | -9 | 1054938 | 298878 | 0.000898226
HG00421 | HG00421 | -9 | 1054938 | 296364 | 0.00462616
HG00422 | HG00422 | -9 | 1054938 | 297204 | -0.00124008
HG00428 | HG00428 | -9 | 1054938 | 293204 | -0.0182342
HG00436 | HG00436 | -9 | 1054938 | 296524 | -0.00656872
HG00437 | HG00437 | -9 | 1054938 | 297147 | -0.0157769
HG00442 | HG00442 | -9 | 1054938 | 297830 | 0.0119195
...
How should such results be interpreted? What is the meaning of a plus or minus score? What do you get when you add up all the scores?
Thank you!

**Comment by getian107** [comment]
Hi - After using PLINK's --score function you will get a risk score for each individual (the SCORESUM column) in your testing dataset. You will then need the phenotypes of these individuals to assess how accurate the prediction is. Some commonly used metrics to assess score performance include variance explained for continuous phenotypes and AUC or odds ratio for binary phenotypes.

**Comment by lhl-0419** [comment]
Thank you for your answer！I may not know PRS very well, and it is still unclear how to use the individual risk scores obtained above to assess the accuracy of predictions. I want to use the AUC to evaluate score performance, how can I do that? I would appreciate it if you could give me a more detailed explanation.

**Comment by getian107** [comment]
Hi - This PRS tutorial may be helpful: https://www.nature.com/articles/s41596-020-0353-1

**Comment by lhl-0419** [comment]
Thank you!
