### ISSUE TITLE
Making sense of the LD reference file for PRS-cs

### ISSUE THREAD

**Issue by jielab** [getian107/PRScs#71]
Hi, guys:

I found that the downloaded **ldblk_1kg_chr1.hdf5** file has **15,584,115** rows, which the LDpred software LD reference file **1.l2.ldscore.gz** only has **106,137** rows. This difference is way too much.  Can someone please let me know the fundamental difference here? 

Below is the first few rows of the **ldblk_1kg_chr1.hdf5** file. Taken the last row for example, what does each of these numbers **(0,0): 1, 0.869622, 0.987995, -0.0976974, 0.823086, -0.00199816**  for?
```
HDF5 "**ldblk_1kg_chr1.hdf5**" {
GROUP "/" {
   GROUP "blk_1" {
      DATASET "ldblk" {
         DATATYPE  H5T_IEEE_F64LE
         DATASPACE  SIMPLE { ( 296, 296 ) / ( 296, 296 ) }
         DATA {
         (0,0): 1, 0.869622, 0.987995, -0.0976974, 0.823086, -0.00199816,
```

Let's say that I have two neighbouring SNPs on chromosome 1, and their base pair positions are **10000**bp and **20000**bp respectively. How to find the LD between these two SNPs from the above HDF5 file?

Thank you very much & best regards,
jie

**Comment by getian107** [comment]
The hdf5 files save the LD matrix for each LD block on a chromosome. The list of variants included in these matrices is provided in the snpinfo_* files. The example you gave here was the LD matrix for the first block on chromosome 1. The first row is simply the first 6 values of the first row of the LD matrix; the second row is the 7th-12th values of the first row of the LD matrix, etc. Once read by the software, this is a 296x296 LD matrix corresponding to the first LD block on chromosome 1.

**Comment by jielab** [comment]
Thanks, Prof. Ge! 

I found that your **snpinfo_mult_1kg_hm3** file has **~1.3 million SNPs**, which has **~100K SNPs for chr1**. Above, I mentioned that your **ldblk_1kg_chr1.hdf5** file has **~15.6 million rows**. Since each row has **6 numbers**, there are a total of **~100 million LD values**, correct? 

But **for ~100K SNPs**, if we do pair-wise LD calculation for all of them, it would be (**100K * 100K / 2**), and this would be ~ 50 times of ~100 million. Wait, maybe only SNP pairs within 1Mb of each other needs to calculate LD. But I did not see how that is specified in your paper.

If you could simply let me know how I could use PLINK or some other tool to generate the **ldblk_1kg_chr1.hdf5** file, then I will go to figure this out myself :- ). 

Finally, it would be great if you could briefly let us know why the LDpred software’s LD reference file **1.l2.ldscore.gz** only has **106,137** rows. Is this why PRS-cs could deal with local LD better than LDpred?

Thanks again!

Jie

**Comment by getian107** [comment]
We divided each chromosome into largely independent blocks, and only calculated and saved the LD matrix for each block. This is described in the PRS-CS paper:

"In practice, we partition the genome into 1703 largely independent genomic regions estimated using data from the 1KG European sample [http://bitbucket.org/nygcresearch/ldetect-data], and conduct multivariate update of the effect sizes
within each LD block."

1.l2.ldscore.gz is used in LD score regression to estimate heritability. You can refer to the original LDSC paper: https://www.nature.com/articles/ng.3211
LDpred uses heritability estimates from LD score regression but also requires the user providing another LD reference panel.
