### ISSUE TITLE
PRS-cs: taking 2 SNPs as an example

### ISSUE THREAD

**Issue by jielab** [getian107/PRScs#72]
Dear Prof. Ge:

I run PRS-cs on the **first 2 SNPs** of the **test_data/sumstats.txt** file that comes with your software.

**Before:** 
SNP     A1      A2      BETA    P
rs9605903       T       C       **-0.011400**       1.602000e-01
rs5746647       G       T       -0.007900       6.000000e-01

**After:**
22      rs9605903       17054720        T       C       **-6.370739e-04**
22      rs5746647       17057138        G       T       **-3.792364e-04**

It seems that PRS-CS **over**-shrinked the effect size, since the **Before** effect size for the 1st SNP alone (**0.0011400**) is greater than the **After** effect size of 2 SNPs combined (**0.001016**).

I know that the above might not be  a good example, since these 2 SNPs are not significant. Now, if I change the P-value of these two SNPs to something very significnat, as below:

**Before:** 
SNP     A1      A2      BETA    P
rs9605903       T       C       -0.011400       **1.602000e-10**
rs5746647       G       T       -0.007900       **6.000000e-10**

**After:** 
22      rs9605903       17054720        T       C       -9.888747e-03
22      rs5746647       17057138        G       T       -1.944407e-02

This time, it seems that PRS-cs **under**-shrinked the effect size, since the **After** effect size of the 2nd SNP alone is greater than the **Before** effect size of 2 SNPs combined.

What do you think of this observation?

It would be great if you could throw some R code on how the continous shrinkage on these 2 SNPs was done, as a very simple example for illustration. The python code is quite complicated, which is necessary for genome-wide analysis.

Thank you & best regards,
Jie

**Comment by getian107** [comment]
You cannot directly compare posterior effect sizes to marginal effect sizes because PRScs converts marginal effects to standardized effects [i.e., the effects under standardized (zero mean and unit variance) phenotype and genotype] before fitting the model. After model fitting, the effects are then converted back to per-allele effects but the phenotype is still assumed to have unit variance.
