### ISSUE TITLE
Slight differences when using OR + P and OR + SE

### ISSUE THREAD

**Issue by cnl27** [getian107/PRScs#75]
Hello,

I carried out two versions of the same analysis, in one case using the GWAS summary statistics with OR + P and in the other case with OR + SE. I noticed that the estimated effect sizes, as well as the PRS that I subsequently calculated, were very highly correlated (> 0.99) but not identical. May this be just related to the number of decimals used in each case?

Thank you.

**Comment by getian107** [comment]
Hi - PRScs is a Bayesian approach and uses MCMC to fit the model which involves random sampling from the posterior distribution. Therefore unless you use the same random seed, running the algorithm twice will produce slightly different results even if all the input and model parameters are identical. As you said, the numerical may contribute to the difference between OR + P and OR + SE as well. I think this is not an issue as long as the resulting PRS are highly correlated.

**Comment by cnl27** [comment]
Hi again,

Thank you for your answer. Indeed, I was using the same seed in both analyses. The differences in the resulting PRS were minimal, but I just wanted to make sure that slight variations are expected.
