### ISSUE TITLE
Specify column names for header in GWAS summary stats file

### ISSUE THREAD

**Issue by samreenzafer** [getian107/PRScs#76]
I see that the GWAS file needs to have the SNP, A1,A2, etc column names.
I would like to be able to specify alternate column names to the PRSCs.py script for the various GWAS summary stats files I have from different sources, without having to actually manipulate each of those GWASes since there are well over 5000 such GWASes, each ~1Gb in size that I'd like to run PRSCs on. 

I see that the parse_genet.py file will need to be changed, where the column names are hardcoded, but I don't have python experience. Could you please provide command line options, or help me modify my own version of that script for my use. 

For example a GWAS i have downloaded from the GWAS Catalog has the following format:
```
zcat GCST90095084_buildGRCh38.tsv.gz|head
chromosome	base_pair_location	variant_id	effect_allele	other_allele	effect_allele_frequency	beta	standard_error	p_value
1	10000044	rs112409036	A	T	0.9712	0.138	0.1285	0.2827
1	100000723	rs11166389	A	G	0.0857	-0.1785	0.0767	0.01994
1	100000839	rs116740877	A	T	0.0116	-0.2411	0.1963	0.2194

```
Thank You.

**Comment by getian107** [comment]
Hi - We do have a plan to provide command line options to select columns but I think it will take a while before we complete implementation and testing. If all the summary statistics files have the same format (or a small number of formats), it might be possible to modify the script and I'm happy to help with that.

**Comment by samreenzafer** [comment]
Hi, Thank you. 
I eventually figured out how to make those changes, and tested it out too. I also added a little code to check if the summary stats file is a 'gzipped' file, which is true for me most of the time, and if so will read the file using 'gzip' package. 
Attached are my scripts if you would like to test them thoroughly too or point out mistakes that could potentially break the algorithm.

[parse_genet_newColNames.py.txt](https://github.com/getian107/PRScs/files/15017869/parse_genet_newColNames.py.txt)
[PRScs_colnames.py.txt](https://github.com/getian107/PRScs/files/15017870/PRScs_colnames.py.txt)

and to run on one of those GWAScatalog summ stats file. 
`python ~/PRScs_colnames.py  --ref_dir=$ref_dir/ldblk_1kg_eur --bim_prefix=$bim_dir/CAU.qc --sst_file=$SUM_STATS_FILE --n_gwas=$GWAS_SAMPLE_SIZE  --out_dir=$out_dir/test.pqtl --SNP=variant_id --A1=effect_allele --A2=other_allele --BETA=beta --P=p_value --SE=standard_error --chrom=22 
`

Also I noticed that, the code is reading in the entire summary stats file twice for every chromosome. Which means if using the default options, it reads in the summary stats file 22*2 = 44 times. This is unnecessarily adding to the run time of the code.  Permutations already makes the code have a high runtime. Can you please address this also ? 

Thank You.

**Comment by samreenzafer** [comment]
I further added some checks in the parse_genet script, to ignore lines in Summary stats file where any of the values are missing. 
[parse_genet_newColNames.py.txt](https://github.com/getian107/PRScs/files/15018716/parse_genet_newColNames.py.txt)

**Comment by getian107** [comment]
Thanks so much for sharing the code! Regarding reading the summary stats: we actually spent a lot of time to optimize the code. The first pass only reads SNP IDs and the two alleles and aligns all SNPs between the summary stats, reference panel and the target dataset. The second pass then reads and parse the full summary stats. Reading and processing the summary stats only takes a small fraction of time when running the algorithm so I don't think it's an issue.
