### ISSUE TITLE
GWAS sample size

### ISSUE THREAD

**Issue by frahimov** [getian107/PRScs#78]
Hello, is there a way to provide sample size for individual variants?

**Comment by getian107** [comment]
The current version does not have this option. That said, PRScs is in general not sensitive to sample size misspecification. We recommend filtering out variants that have a very different sample size (e.g., those with <50% of the total sample size), and then use total sample size or median sample size as the input.

**Comment by frahimov** [comment]
Thank you for your reply and suggestion.
