### ISSUE TITLE
Script cannot read --sst_file

### ISSUE THREAD

**Issue by kllrdr** [getian107/PRScs#79]
I keep getting this error:
``* Please specify the summary statistics file using --sst_file``
However, I set the permissions, I made sure I list the directory correctly, and the file contains the correct input.
My script:
``python3 PRScs.py \
--ref_dir=PRScs \
--bim_prefix=all_snps \ 
--sst_file=sumstats.txt \ 
--n_gwas=128171 \
--pop=EUR \
--out_dir=/PRS/ \
--out_name=results_may2024``

Can you please help me what could be the issue? Thank you so much in advance!

**Comment by getian107** [comment]
Hi - It seems that you may have confused PRS-CSx commands with PRS-CS. You need to specify the reference population using `--ref_dir`, e.g., `--ref_dir=path_to_ref/ldblk_1kg_eur`, and PRS-CS doesn't have a `--pop` flag.

**Comment by kllrdr** [comment]
Thank you so much for the fast response!
I changed ref_dir and deleted the pop flag, and now I experience a different error: ``Option not recognized``
``python3 PRScs.py \
--ref_dir=ldblk_1kg_eur \
--bim_prefix=all_snps \
--sst_file=sumstats.txt \
--n_gwas=128171 \
--out_dir=PRS/ \
--out_name=results_may2024``

**Comment by getian107** [comment]
PRS-CS also doesn't have a `--out_name` flag.

**Comment by kllrdr** [comment]
Thank you so much!!
