### ISSUE TITLE
Pathway PRS using PRScs

### ISSUE THREAD

**Issue by dagherlab** [getian107/PRScs#80]
Hi!
In PRSice, PRSet can calculate PRS for a gene set. can we also do sth similar using PRScs?

thank you!
Lang

**Comment by getian107** [comment]
Hi Lang - After obtaining posterior SNP effect sizes using PRScs, you can use SNPs located in a pathway to calculate pathway PRS.

**Comment by dagherlab** [comment]
thank you for your quick response! yes this is what I'm looking for.

**Comment by cnl27** [comment]
Sorry to comment on this closed thread.

Could this be done the other way around? I mean, selecting the SNPs of interest in the first place and then calculate the posterior effect sizes only for those SNPs. Or would this be methodologically incorrect?

Thank you.
