### ISSUE TITLE
Phenotype of test_data 

### ISSUE THREAD

**Issue by huthvincent** [getian107/PRScs#81]
Hi Tian,

I really appreciate your work and find your paper very insightful. However, I encountered some difficulties while testing the code. I noticed that you provided several datasets in the `/test_data` folder, including three `.txt` files with summary statistics. I understand that these files contain the effect sizes and p-values for each SNP obtained from GWAS.

Could you please clarify which phenotype these GWAS statistics were derived from?

I am new to the PRS field and would greatly appreciate any guidance you could provide.

Thank you very much!

**Comment by getian107** [comment]
Hi -- These are just randomly generated GWAS summary statistics. The goal was to use these test data to get the software running rather than producing any meaningful prediction for a specific phenotype.

**Comment by huthvincent** [comment]
Thanks a lot!
