### ISSUE TITLE
LinAlgError("SVD did not converge")

### ISSUE THREAD

**Issue by ckhunsr1** [getian107/PRScs#82]
Hello,

I have occasionally run into below problem when using PRSCS:

##### process chromosome 18 #####
... parse reference file: /xx/snpinfo_1kg_hm3 ...
... 33336 SNPs on chromosome 18 read from /xx/snpinfo_1kg_hm3 ...
... parse bim file: /xx/1000g_hm3.bim ...
... 31006 SNPs on chromosome 18 read from /xx/1000g_hm3.bim ...
... parse sumstats file: /xx/ss.txt ...
... 1008598 SNPs read from /xx/ss.txt ...
... 26623 common SNPs in the reference, sumstats, and validation set ...
... parse reference LD on chromosome 18 ...
Traceback (most recent call last):
  File "/xx/PRScs.py", line 118, in <module>
    main()
  File "/xx/PRScs.py", line 108, in main
    ld_blk, blk_size = parse_genet.parse_ldblk(param_dict['ref_dir'], sst_dict, int(chrom))
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/xx/parse_genet.py", line 186, in parse_ldblk
    _, s, v = linalg.svd(ld_blk[blk])
              ^^^^^^^^^^^^^^^^^^^^^^^
  File "/xx/.conda/envs/prscs/lib/python3.12/site-packages/scipy/linalg/_decomp_svd.py", line 145, in svd
    raise LinAlgError("SVD did not converge")
numpy.linalg.LinAlgError: SVD did not converge

Would you please let me know how to fix this issue? Thank you!

**Comment by getian107** [comment]
Hi - Thanks for reaching out! This is an error that we have never encountered before.
A couple of questions to help diagnose:
- Did this happen for different GWAS inputs or for a specific GWAS?
- Did this error occur every time if you rerun the program on the same dataset (with the same or a different random seed)?
If possible it would also be helpful to know if using a different python version resolves the problem.
Thanks!

**Comment by ckhunsr1** [comment]
Hello,

This happened for different GWAS inputs with whatever seeds. Interestingly, it only happened on chromosome 18. Because of this, I tried using a ukb ref panel instead of 1000g ref panel and this actually solved the problem.

Thanks!

**Comment by getian107** [comment]
Based on your description, I suspect that the 1kg reference panel for chr 18 may be incomplete or corrupted. Re-downloading the panel could potentially resolve the issue.

**Comment by ckhunsr1** [comment]
I just confirmed that the 1kg reference file I used was not corrupted.

**Comment by getian107** [comment]
OK - Let me know if you keep running into this error and want to fix it. The UKBB reference panel should perform highly similarly in most cases.
