### ISSUE TITLE
Documentation clarification: How are blocks defined all 5 populations?

### ISSUE THREAD

**Issue by shz9** [getian107/PRScs#83]
Hi there,

In the [Notes](https://www.dropbox.com/scl/fi/i4ct71xyguo1ju1h3hche/UKBB_ref.txt?rlkey=ujvuzteiib3rf4p5qke3pbzlv&e=1&dl=0) describing how the LD reference panels were constructed from the UK Biobank, you state the following:

> Define LD blocks using pre-computed cutoff points (http://bitbucket.org/nygcresearch/ldetect-data; AFR: 2,582 blocks; ASN: 1,445 blocks; EUR: 1,703 blocks)

However, LDetect only provides blocks for 3 of the 5 superpopulations defined in the 1000G project (`AFR`, `ASN`, `EUR`). So, I'm wondering which blocks did you use for `SAS` and `AMR` samples?

Thank you!

Shadi

**Comment by getian107** [comment]
Hi Shadi - We used ASN cutoff points for SAS and AFR cutoff points for AMR as approximations.
