### ISSUE TITLE
Combined LD reference panel

### ISSUE THREAD

**Issue by HelenYSLin** [getian107/PRScs#86]
Hi Tian,

I am working on a few phenotypes from UK Biobank GWAS sumstats as my discovery data. Since I've chosen the meta-analyzed ones from multi-ancestries, I should use an LD reference panel that includes everyone regardless of ancestry, right? If so, do you have an LD reference panel constructed from everyone together in the UK Biobank? Alternatively, could you provide guidance on how to combine existing reference panels? Thank you.

**Comment by getian107** [comment]
Hi - In the case of meta-GWAS combining data from multiple ancestries, we recommend using the reference panel that matches the ancestry with the largest sample size (which is often European). This is not perfect but usually produces reasonable results. A more principled approach to model multi-ancestry data is to use PRS-CSx if you have access to ancestry-specific GWAS.

**Comment by HelenYSLin** [comment]
Thank you for your suggestion. Asking because we are benchmarking a few PRS methods and would like to keep the reference panel as consistent as possible across methods. Looking at the ancestry-specific HDF5 files, I assume it's difficult to simply combine the existing five sets of files, as this would require recalculating LD from scratch, right?
Also, we might want to continue using discovery data from multi-ancestry meta-analyses, but we'd love to try PRS-CSx for other use cases in the future!

**Comment by getian107** [comment]
Yes you're correct - to construct a multi-ancestry reference panel, LD matrices need to be recomputed from combined individual-level data, and it's unclear what cutoff points should be used to define LD blocks. Given that many people apply PRS-CS to meta-GWAS, it may be helpful to benchmark how this approach performs in practice.

**Comment by HelenYSLin** [comment]
Got it. Thanks so much!

**Comment by NicolasC0** [comment]
Hey guys, I'm also working with a multi-ancestry GWAS and I'd just like a follow up on this issue! @HelenYSLin did you proceed with the LD reference of the majority of the GWAS?

Thank you!
