### ISSUE TITLE
phi being excluded from prior

### ISSUE THREAD

**Issue by heliziii** [getian107/PRScs#87]
Hi,

Thank you for your great tool! I have a question regarding one difference between the main text and supplementary + code. Equation 6 in the main paper has both global and local shrinkage factors in the prior for beta:

<img width="805" alt="Screenshot 2024-10-11 at 9 44 01 AM" src="https://github.com/user-attachments/assets/3ae82678-ccc1-4379-8500-151b8c7407e3">

While in the supplementary and I believe in the [code as well](https://github.com/getian107/PRScs/blob/f86d5c7a0b4cc08561b9bcb887b8604c61563545/mcmc_gtb.py#L59), phi is excluded from the prior:

<img width="196" alt="Screenshot 2024-10-11 at 9 45 32 AM" src="https://github.com/user-attachments/assets/fa04347a-ee98-4823-8970-65288c6dc969">

I would appreciate your clarification on this, was there a specific reason for removing the phi from the equation?

Best,
Helia

**Comment by getian107** [comment]
Hi Helia - phi was pushed to the prior of psi in the supplementary, i.e.,

psi_j ~ Gamma(a, delta_j),   delta_j ~ Gamma(b, phi)

You can prove that marginally the prior on beta does not change.

In the main text, we wanted to make it clearer for the reader that the prior of beta depends on both local and global shrinkage. The version in the supplementary is what we actually implemented I believe. Sorry for the inconsistency and confusion.
