### ISSUE TITLE
GWAS sample size

### ISSUE THREAD

**Issue by AngeloArias97** [getian107/PRScs#90]
Hi Getian,

I'm using PRScs for calculating a score in schizophrenia, I'm doubting which sample size should I use (NCAS + NCON) or NEFF? Would the results differ that much if I use NCAS+NCON? What happen with those variants that have different NEFFs? In previous posts I read that you recommended to exclude those variants that differ >50% from the total sample size, is this the NCAS+NCON sample size?

Thank you so much for developing such an amazing tool :)

**Comment by getian107** [comment]
Hi - I'd recommend using NEFF but PRScs is generally robust to this parameter so using the total sample size usually doesn't make a big difference. The goal of sample size based filtering is to remove SNPs that are missing from many cohorts; >30% or >50% of the total sample size is a reasonable way to do this but you can also filter based on e.g. the number of cohorts that have the SNP. Again, PRScs is not very sensitive to sample size variation across SNPs so this will probably have limited impact on prediction accuracy either.

**Comment by AngeloArias97** [comment]
Thank so much! All clear now :)
